ignore:
    - "**/*.pb.go"
    - "**testInitializerInputs.go"
    - "**testInitializerVMOutput.go"
    - "**hosttest/**"
    - "**mock/**"
    - "**scenario/**"
    - "**test/**"
    - "**testcommon/**"
    - "**testgen/**"
