package vmhooksgenerate

// WriteWasmer2OpcodeCost generates code for wasmer2/opcodeCost.go
func WriteWasmer2OpcodeCost(out *eiGenWriter) {
	allowedOpcodes := LoadOpcodeNames()
	maxNameLength := allowedOpcodes.MaxNameLength()

	autoGeneratedHeader(out)

	out.WriteString(`
package wasmer2

import "github.com/multiversx/mx-chain-vm-go/executor"

type OpcodeCost struct {`)

	for _, opcode := range allowedOpcodes.RelevantCodes {
		out.WriteString("\n\t")
		out.WriteString(opcode)
		for i := len(opcode); i < maxNameLength; i++ {
			out.WriteString(" ")
		}
		out.WriteString(" uint32")
	}

	out.WriteString(`
}

func (wasmerExecutor *Wasmer2Executor) extractOpcodeCost(wasmOps *executor.WASMOpcodeCost) *OpcodeCost {
	return &OpcodeCost{`)

	for _, opcode := range allowedOpcodes.RelevantCodes {
		out.WriteString("\n\t\t")
		out.WriteString(opcode)
		out.WriteString(":")
		for i := len(opcode); i < maxNameLength; i++ {
			out.WriteString(" ")
		}
		out.WriteString(" wasmOps.")
		out.WriteString(opcode)
		out.WriteString(",")
		// out.WriteString(fmt.Sprintf("\t\t%s: wasmOps.%s,\n", opcode, opcode))
	}

	out.WriteString("\n\t}\n")
	out.WriteString("}\n")
}
