package vmhooksgenerate

import (
	"fmt"
)

func WriteNames(
	out *eiGenWriter,
	packageName string,
	eiMetadata *EIMetadata,
) {
	autoGeneratedGoHeader(out, packageName)
	out.WriteString(`
var empty struct{}

var functionNames = map[string]struct{}{`)

	for _, funcMetadata := range eiMetadata.AllFunctions {
		out.WriteString(fmt.Sprintf("\n\t\"%s\": empty,", lowerInitial(funcMetadata.Name)))
	}

	out.WriteString(`
}
`)
}
