package vmhooksgenerate

import (
	"bufio"
	"fmt"
	"os"
)

// WriteEVMOpcodeCostConfigHelpers generates code for config.txt
// (to be copied manually in config/config.toml)
func WriteEVMOpcodeCostConfigHelpers(out *eiGenWriter) {
	out.WriteString(`// Code generated by vmhooks generator. DO NOT EDIT.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!! AUTO-GENERATED FILE !!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

// !!!!!!!!!!!!!!!!!! USE IN config/config.toml !!!!!!!!!!!!!!!!!!!!

`)
	out.WriteString("[EVMOpcodeCost]\n")
	readFile, err := os.Open("generate/cmd/input/evm_opcodes.txt")
	if err != nil {
		panic(err)
	}
	defer readFile.Close()

	fileScanner := bufio.NewScanner(readFile)
	fileScanner.Split(bufio.ScanLines)

	for fileScanner.Scan() {
		opcode := fileScanner.Text()
		out.WriteString(fmt.Sprintf("    %s = 1\n", opcode))
	}
}
