package vmhooksgenerate

import (
	"bufio"
	"fmt"
	"os"
)

// WriteOpcodeCostFuncHelpers generates code for extractOpcodeCost.txt
// (to be copied manually in wasmer2/wasmer2Executor.go)
func WriteOpcodeCostFuncHelpers(out *eiGenWriter) {
	out.WriteString(`// Code generated by vmhooks generator. DO NOT EDIT.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!! AUTO-GENERATED FILE !!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

// !!!!!!!!!!!!!!! USE IN wasmer2/wasmer2Executor.go !!!!!!!!!!!!!!!

`)
	out.WriteString("func (wasmerExecutor *Wasmer2Executor) extractOpcodeCost(wasmOps *executor.WASMOpcodeCost) *OpcodeCost {\n")
	out.WriteString("\treturn &OpcodeCost {\n")

	readFile, err := os.Open("generate/cmd/input/wasmer2_opcodes_short.txt")
	if err != nil {
		panic(err)
	}
	defer readFile.Close()

	fileScanner := bufio.NewScanner(readFile)
	fileScanner.Split(bufio.ScanLines)

	for fileScanner.Scan() {
		opcode := fileScanner.Text()
		out.WriteString(fmt.Sprintf("\t\t%s: wasmOps.%s,\n", opcode, opcode))
	}
	out.WriteString("\t}\n")
	out.WriteString("}\n")
}
