package vmhooksgenerate

import (
	"bufio"
	"fmt"
	"os"
)

// WriteEVMOpcodeCostHelpers generates code for FillGasMap_EVMOpcodeCosts.txt
// (to be copied manually in config/gasSchedule.go)
func WriteEVMOpcodeCostFuncHelpers(out *eiGenWriter) {
	out.WriteString(`// Code generated by vmhooks generator. DO NOT EDIT.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!! AUTO-GENERATED FILE !!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

// !!!!!!!!!!!!!!!!!! USE IN config/gasSchedule.go !!!!!!!!!!!!!!!!!

`)
	out.WriteString("func FillGasMap_EVMOpcodeCosts(value uint64) map[string]uint64 {\n")
	out.WriteString("\tgasMap := make(map[string]uint64)\n\n")

	readFile, err := os.Open("generate/cmd/input/evm_opcodes.txt")
	if err != nil {
		panic(err)
	}
	defer readFile.Close()

	fileScanner := bufio.NewScanner(readFile)
	fileScanner.Split(bufio.ScanLines)

	for fileScanner.Scan() {
		opcode := fileScanner.Text()
		out.WriteString(fmt.Sprintf("\tgasMap[\"%s\"] = value\n", opcode))
	}
	out.WriteString("\n\treturn gasMap\n")
	out.WriteString("}\n")
}
