package vmhooksgenerate

import (
	"fmt"
)

// WriteWasmer2OpcodeCost generates code for wasmer2/opcodeCost.go
func WriteWasmer2OpcodeCost(out *eiGenWriter) {

	out.WriteString(`// Code generated by vmhooks generator. DO NOT EDIT.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!! AUTO-GENERATED FILE !!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

`)
	out.WriteString("package wasmer2\n\n")
	out.WriteString("type OpcodeCost struct {\n")

	allowedOpcodes := LoadOpcodeNames()

	for _, opcode := range allowedOpcodes.RelevantCodes {
		out.WriteString(fmt.Sprintf("\t%-30suint32\n", opcode))
	}

	out.WriteString("}\n")
}
