package vmhooksgenerate

import (
	"fmt"
)

// WriteRustVMHooksLegacyTrait autogenerate data in the provided file
func WriteRustVMHooksTrait(out *eiGenWriter, eiMetadata *EIMetadata) {
	autoGeneratedHeader(out)
	out.WriteString(`
use crate::{MemLength, MemPtr, VMHooksEarlyExit};

#[rustfmt::skip]
#[allow(clippy::too_many_arguments)]
pub trait VMHooks: core::fmt::Debug {
`)

	for _, funcMetadata := range eiMetadata.AllFunctions {
		out.WriteString(fmt.Sprintf(
			"    fn %s%s;\n",
			snakeCase(funcMetadata.Name),
			writeRustFnDeclarationArguments(
				"&mut self",
				funcMetadata,
				rustVMHooksType,
				rustVMHooksReturnType,
			),
		))
	}

	out.WriteString(`}

/// Dummy implementation for VMHooks. Can be used as placeholder, or in tests.
#[derive(Debug)]
pub struct VMHooksDefault;

#[allow(unused)]
#[rustfmt::skip]
impl VMHooks for VMHooksDefault {
`)

	for i, funcMetadata := range eiMetadata.AllFunctions {
		if i > 0 {
			out.WriteString("\n")
		}

		out.WriteString(fmt.Sprintf(
			"    fn %s%s {\n",
			snakeCase(funcMetadata.Name),
			writeRustFnDeclarationArguments(
				"&mut self",
				funcMetadata,
				rustVMHooksType,
				rustVMHooksReturnType,
			),
		))

		out.WriteString(fmt.Sprintf(
			"        println!(\"Called: %s\");\n",
			snakeCase(funcMetadata.Name),
		))

		if funcMetadata.Result == nil {
			out.WriteString("        Ok(())\n")
		} else {
			out.WriteString("        Ok(0)\n")
		}

		out.WriteString("    }\n")
	}

	out.WriteString("}\n")

}
