package vmhooksgenerate

import (
	"fmt"
	"strings"
)

// WriteRustWasmerOpcodeCost generates code for wasmer_opcode_cost.rs
func WriteRustWasmerOpcodeCost(out *eiGenWriter) {
	autoGeneratedHeader(out)
	out.WriteString("\nuse crate::Cost;")
	out.WriteString("\nuse crate::executor_interface::{OpcodeConfig, OpcodeCost, OpcodeVersion};")
	writeOpcodeCostBody(out, true)

}

// WriteRustWasmerExperimentalOpcodeCost generates code for we_opcode_cost.rs
func WriteRustWasmerExperimentalOpcodeCost(out *eiGenWriter) {
	autoGeneratedHeader(out)
	out.WriteString("\nuse super::Cost;")
	out.WriteString("\nuse multiversx_chain_vm_executor::{OpcodeConfig, OpcodeCost, OpcodeVersion};")
	writeOpcodeCostBody(out, false)
}

func writeOpcodeCostBody(out *eiGenWriter, allowUnwind bool) {
	allowedOpcodes := LoadOpcodeNames()

	out.WriteString(`
use wasmer::wasmparser::Operator;

pub fn get_opcode_cost(op: &Operator, opcode_config: &OpcodeConfig) -> Cost {
    match opcode_config.opcode_version {
        OpcodeVersion::V1 => get_opcode_cost_v1(op, &opcode_config.opcode_cost),
        OpcodeVersion::V2 => get_opcode_cost_v2(op, &opcode_config.opcode_cost),
    }
}

#[rustfmt::skip]
fn get_opcode_cost_v1(op: &Operator, opcode_cost: &OpcodeCost) -> Cost {
    match op {
`)

	for _, opcodeName := range allowedOpcodes.AllowedV1 {
		writeOperatorMatchArm(out, allowUnwind, allowedOpcodes, opcodeName)
	}

	out.WriteString(`        _ => Cost::Illegal,
    }
}

#[rustfmt::skip]
fn get_opcode_cost_v2(op: &Operator, opcode_cost: &OpcodeCost) -> Cost {
    match op {
`)

	for _, opcodeName := range allowedOpcodes.AllowedV2 {
		writeOperatorMatchArm(out, allowUnwind, allowedOpcodes, opcodeName)
	}

	out.WriteString(`        _ => Cost::Illegal,
    }
}
`)

}

func writeOperatorMatchArm(out *eiGenWriter, allowUnwind bool, allowedOpcodes *OpcodeNames, opcodeName string) {
	if !allowUnwind && opcodeName == "Unwind" {
		out.WriteString("        // Operator::Unwind { .. } => Cost::Base(opcode_cost.opcode_unwind), // unwind no longer available in Wasmer 6\n")
		return
	}

	if allowedOpcodes.IsPerByteOpcode(opcodeName) {
		writeBulkMemoryMatchArm(out, opcodeName)
		return
	}

	writeMatchArm(out, opcodeName, fmt.Sprintf("Cost::Base(opcode_cost.opcode_%s)", strings.ToLower(opcodeName)))
}

func writeBulkMemoryMatchArm(out *eiGenWriter, opcodeName string) {
	writeMatchArm(out, opcodeName, fmt.Sprintf("Cost::BulkMemory { base: opcode_cost.opcode_%s, per_byte: opcode_cost.opcode_%s }",
		strings.ToLower(opcodeName), strings.ToLower(PerByteCostName(opcodeName))))
}

// writeMatchArm writes one line per operator, the match functions are rustfmt::skip-ed.
func writeMatchArm(out *eiGenWriter, opcodeName string, armBody string) {
	out.WriteString(fmt.Sprintf("        Operator::%s { .. } => %s,\n", opcodeName, armBody))
}
