package vmhooksgenerate

import (
	"fmt"
)

func WriteRustHookNames(
	out *eiGenWriter,
	eiMetadata *EIMetadata,
) {
	autoGeneratedHeader(out)
	out.WriteString("\n")
	out.WriteString("pub const EI_1_5_NAMES: &[&str] = &[")

	for _, funcMetadata := range eiMetadata.AllFunctions {
		out.WriteString(fmt.Sprintf("\n    \"%s\",", lowerInitial(funcMetadata.Name)))
	}

	out.WriteString(`
];
`)
}
