package vmhooksgenerate

import (
	"fmt"
	"strings"
)

// WriteRustCapiOpcodeCost generates code for capi_opcode_cost.rs
func WriteRustCapiOpcodeCost(out *eiGenWriter) {
	autoGeneratedHeader(out)
	out.WriteString("\nuse multiversx_chain_vm_executor::OpcodeCost;\n\n")
	out.WriteString("/// FFI-safe mirror of `OpcodeCost`.\n")
	out.WriteString("///\n")
	out.WriteString("/// This is a distinct type rather than a cast of `OpcodeCost` itself, so that\n")
	out.WriteString("/// the general-purpose struct is free to change shape without touching the C\n")
	out.WriteString("/// ABI, and vice versa.\n")
	out.WriteString("#[allow(non_camel_case_types)]\n")
	out.WriteString("#[repr(C)]\n")
	out.WriteString("pub struct vm_exec_opcode_cost_t {\n")

	costNames := LoadOpcodeNames().AllCostNames()

	for _, opcode := range costNames {
		out.WriteString(fmt.Sprintf("    pub opcode_%s: u32,\n", strings.ToLower(opcode)))
	}

	out.WriteString("}\n\n")
	out.WriteString("impl vm_exec_opcode_cost_t {\n")
	out.WriteString("    pub(crate) fn to_opcode_cost(&self) -> OpcodeCost {\n")
	out.WriteString("        OpcodeCost {\n")

	for _, opcode := range costNames {
		fieldName := strings.ToLower(opcode)
		out.WriteString(fmt.Sprintf("            opcode_%s: self.opcode_%s,\n", fieldName, fieldName))
	}

	out.WriteString("        }\n")
	out.WriteString("    }\n")
	out.WriteString("}\n")
}
