package vmhooksgenerate

import (
	"bufio"
	"fmt"
	"os"
)

// WriteExecutorOpcodeCost generates code for executor/gasCostWASM.go
func WriteExecutorOpcodeCost(out *eiGenWriter) {
	out.WriteString(`// Code generated by vmhooks generator. DO NOT EDIT.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!! AUTO-GENERATED FILE !!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

`)
	out.WriteString("package executor\n\n")
	out.WriteString("type WASMOpcodeCost struct {\n")

	readFile, err := os.Open("generate/cmd/input/wasm_opcodes.txt")
	if err != nil {
		panic(err)
	}
	defer readFile.Close()

	fileScanner := bufio.NewScanner(readFile)
	fileScanner.Split(bufio.ScanLines)

	for fileScanner.Scan() {
		opcode := fileScanner.Text()
		out.WriteString(fmt.Sprintf("\t%-30suint32\n", opcode))
	}
	out.WriteString("}\n")
}
