@baseUrl = http://localhost:9091
@contractsFolder = {{$processEnv HOME}}/Desktop/workspaces/go/mx-chain-vm-go/test/contracts
@alice = AA000000000000000000000000000000000000000000000000000000000000AA
@bob = BB000000000000000000000000000000000000000000000000000000000000BB
@contractAddress = 636f6e74726163743000000000000000000000000000000000000000000000aa

###

POST {{baseUrl}}/account HTTP/1.1
Content-Type: application/json

{
    "AddressHex": "{{alice}}",
    "Balance": "100000",
    "Nonce": 0
}

###

# COUNTER: deploy
POST {{baseUrl}}/deploy HTTP/1.1
Content-Type: application/json

{
    "ImpersonatedHex": "{{alice}}",
    "CodePath": "{{contractsFolder}}/counter/output/counter.wasm"
}

###

# COUNTER: increment
POST {{baseUrl}}/run HTTP/1.1
Content-Type: application/json

{
    "ImpersonatedHex": "{{alice}}",
    "ContractAddressHex": "{{contractAddress}}",
    "Function": "increment"
}

###

# COUNTER: decrement
POST {{baseUrl}}/run HTTP/1.1
Content-Type: application/json

{
    "ImpersonatedHex": "{{alice}}",
    "ContractAddressHex": "{{contractAddress}}",
    "Function": "decrement"
}

###

# COUNTER: get value
POST {{baseUrl}}/query HTTP/1.1
Content-Type: application/json

{
    "ImpersonatedHex": "{{alice}}",
    "ContractAddressHex": "{{contractAddress}}",
    "Function": "get"
}

###

# COUNTER => ERC20 (upgrade)

POST {{baseUrl}}/upgrade HTTP/1.1
Content-Type: application/json

{
    "ImpersonatedHex": "{{alice}}",
    "ContractAddressHex": "{{contractAddress}}",
    "CodePath": "{{contractsFolder}}/erc20/output/erc20.wasm",
    "ArgumentsHex": ["64"]
}

###

# ERC20: get totalSupply
POST {{baseUrl}}/query HTTP/1.1
Content-Type: application/json

{
    "ImpersonatedHex": "{{alice}}",
    "ContractAddressHex": "{{contractAddress}}",
    "Function": "totalSupply"
}

###

# ERC20: transferToken
POST {{baseUrl}}/run HTTP/1.1
Content-Type: application/json

{
    "ImpersonatedHex": "{{alice}}",
    "ContractAddressHex": "{{contractAddress}}",
    "Function": "transferToken",
    "ArgumentsHex": ["{{bob}}", "0A"]
}

###

# ERC20: get balanceOf alice
POST {{baseUrl}}/query HTTP/1.1
Content-Type: application/json

{
    "ImpersonatedHex": "{{alice}}",
    "ContractAddressHex": "{{contractAddress}}",
    "Function": "balanceOf",
    "ArgumentsHex": ["{{alice}}"]
}

###

# ERC20: get balanceOf bob
POST {{baseUrl}}/query HTTP/1.1
Content-Type: application/json

{
    "ImpersonatedHex": "{{alice}}",
    "ContractAddressHex": "{{contractAddress}}",
    "Function": "balanceOf",
    "ArgumentsHex": ["{{bob}}"]
}

###
