package config

import "github.com/ElrondNetwork/go-ext-wasm/wasmer"

func FillGasMapWithWASMOpcodeValues(gasMap map[string]uint64, value uint64) map[string]uint64 {
	gasMap["Unreachable"] = value
	gasMap["Nop"] = value
	gasMap["Block"] = value
	gasMap["Loop"] = value
	gasMap["If"] = value
	gasMap["Else"] = value
	gasMap["End"] = value
	gasMap["Br"] = value
	gasMap["BrIf"] = value
	gasMap["BrTable"] = value
	gasMap["Return"] = value
	gasMap["Call"] = value
	gasMap["CallIndirect"] = value
	gasMap["Drop"] = value
	gasMap["Select"] = value
	gasMap["GetLocal"] = value
	gasMap["SetLocal"] = value
	gasMap["TeeLocal"] = value
	gasMap["GetGlobal"] = value
	gasMap["SetGlobal"] = value
	gasMap["I32Load"] = value
	gasMap["I64Load"] = value
	gasMap["F32Load"] = value
	gasMap["F64Load"] = value
	gasMap["I32Load8S"] = value
	gasMap["I32Load8U"] = value
	gasMap["I32Load16S"] = value
	gasMap["I32Load16U"] = value
	gasMap["I64Load8S"] = value
	gasMap["I64Load8U"] = value
	gasMap["I64Load16S"] = value
	gasMap["I64Load16U"] = value
	gasMap["I64Load32S"] = value
	gasMap["I64Load32U"] = value
	gasMap["I32Store"] = value
	gasMap["I64Store"] = value
	gasMap["F32Store"] = value
	gasMap["F64Store"] = value
	gasMap["I32Store8"] = value
	gasMap["I32Store16"] = value
	gasMap["I64Store8"] = value
	gasMap["I64Store16"] = value
	gasMap["I64Store32"] = value
	gasMap["MemorySize"] = value
	gasMap["MemoryGrow"] = value
	gasMap["I32Const"] = value
	gasMap["I64Const"] = value
	gasMap["F32Const"] = value
	gasMap["F64Const"] = value
	gasMap["RefNull"] = value
	gasMap["RefIsNull"] = value
	gasMap["I32Eqz"] = value
	gasMap["I32Eq"] = value
	gasMap["I32Ne"] = value
	gasMap["I32LtS"] = value
	gasMap["I32LtU"] = value
	gasMap["I32GtS"] = value
	gasMap["I32GtU"] = value
	gasMap["I32LeS"] = value
	gasMap["I32LeU"] = value
	gasMap["I32GeS"] = value
	gasMap["I32GeU"] = value
	gasMap["I64Eqz"] = value
	gasMap["I64Eq"] = value
	gasMap["I64Ne"] = value
	gasMap["I64LtS"] = value
	gasMap["I64LtU"] = value
	gasMap["I64GtS"] = value
	gasMap["I64GtU"] = value
	gasMap["I64LeS"] = value
	gasMap["I64LeU"] = value
	gasMap["I64GeS"] = value
	gasMap["I64GeU"] = value
	gasMap["F32Eq"] = value
	gasMap["F32Ne"] = value
	gasMap["F32Lt"] = value
	gasMap["F32Gt"] = value
	gasMap["F32Le"] = value
	gasMap["F32Ge"] = value
	gasMap["F64Eq"] = value
	gasMap["F64Ne"] = value
	gasMap["F64Lt"] = value
	gasMap["F64Gt"] = value
	gasMap["F64Le"] = value
	gasMap["F64Ge"] = value
	gasMap["I32Clz"] = value
	gasMap["I32Ctz"] = value
	gasMap["I32Popcnt"] = value
	gasMap["I32Add"] = value
	gasMap["I32Sub"] = value
	gasMap["I32Mul"] = value
	gasMap["I32DivS"] = value
	gasMap["I32DivU"] = value
	gasMap["I32RemS"] = value
	gasMap["I32RemU"] = value
	gasMap["I32And"] = value
	gasMap["I32Or"] = value
	gasMap["I32Xor"] = value
	gasMap["I32Shl"] = value
	gasMap["I32ShrS"] = value
	gasMap["I32ShrU"] = value
	gasMap["I32Rotl"] = value
	gasMap["I32Rotr"] = value
	gasMap["I64Clz"] = value
	gasMap["I64Ctz"] = value
	gasMap["I64Popcnt"] = value
	gasMap["I64Add"] = value
	gasMap["I64Sub"] = value
	gasMap["I64Mul"] = value
	gasMap["I64DivS"] = value
	gasMap["I64DivU"] = value
	gasMap["I64RemS"] = value
	gasMap["I64RemU"] = value
	gasMap["I64And"] = value
	gasMap["I64Or"] = value
	gasMap["I64Xor"] = value
	gasMap["I64Shl"] = value
	gasMap["I64ShrS"] = value
	gasMap["I64ShrU"] = value
	gasMap["I64Rotl"] = value
	gasMap["I64Rotr"] = value
	gasMap["F32Abs"] = value
	gasMap["F32Neg"] = value
	gasMap["F32Ceil"] = value
	gasMap["F32Floor"] = value
	gasMap["F32Trunc"] = value
	gasMap["F32Nearest"] = value
	gasMap["F32Sqrt"] = value
	gasMap["F32Add"] = value
	gasMap["F32Sub"] = value
	gasMap["F32Mul"] = value
	gasMap["F32Div"] = value
	gasMap["F32Min"] = value
	gasMap["F32Max"] = value
	gasMap["F32Copysign"] = value
	gasMap["F64Abs"] = value
	gasMap["F64Neg"] = value
	gasMap["F64Ceil"] = value
	gasMap["F64Floor"] = value
	gasMap["F64Trunc"] = value
	gasMap["F64Nearest"] = value
	gasMap["F64Sqrt"] = value
	gasMap["F64Add"] = value
	gasMap["F64Sub"] = value
	gasMap["F64Mul"] = value
	gasMap["F64Div"] = value
	gasMap["F64Min"] = value
	gasMap["F64Max"] = value
	gasMap["F64Copysign"] = value
	gasMap["I32WrapI64"] = value
	gasMap["I32TruncSF32"] = value
	gasMap["I32TruncUF32"] = value
	gasMap["I32TruncSF64"] = value
	gasMap["I32TruncUF64"] = value
	gasMap["I64ExtendSI32"] = value
	gasMap["I64ExtendUI32"] = value
	gasMap["I64TruncSF32"] = value
	gasMap["I64TruncUF32"] = value
	gasMap["I64TruncSF64"] = value
	gasMap["I64TruncUF64"] = value
	gasMap["F32ConvertSI32"] = value
	gasMap["F32ConvertUI32"] = value
	gasMap["F32ConvertSI64"] = value
	gasMap["F32ConvertUI64"] = value
	gasMap["F32DemoteF64"] = value
	gasMap["F64ConvertSI32"] = value
	gasMap["F64ConvertUI32"] = value
	gasMap["F64ConvertSI64"] = value
	gasMap["F64ConvertUI64"] = value
	gasMap["F64PromoteF32"] = value
	gasMap["I32ReinterpretF32"] = value
	gasMap["I64ReinterpretF64"] = value
	gasMap["F32ReinterpretI32"] = value
	gasMap["F64ReinterpretI64"] = value
	gasMap["I32Extend8S"] = value
	gasMap["I32Extend16S"] = value
	gasMap["I64Extend8S"] = value
	gasMap["I64Extend16S"] = value
	gasMap["I64Extend32S"] = value
	gasMap["I32TruncSSatF32"] = value
	gasMap["I32TruncUSatF32"] = value
	gasMap["I32TruncSSatF64"] = value
	gasMap["I32TruncUSatF64"] = value
	gasMap["I64TruncSSatF32"] = value
	gasMap["I64TruncUSatF32"] = value
	gasMap["I64TruncSSatF64"] = value
	gasMap["I64TruncUSatF64"] = value
	gasMap["MemoryInit"] = value
	gasMap["DataDrop"] = value
	gasMap["MemoryCopy"] = value
	gasMap["MemoryFill"] = value
	gasMap["TableInit"] = value
	gasMap["ElemDrop"] = value
	gasMap["TableCopy"] = value
	gasMap["TableGet"] = value
	gasMap["TableSet"] = value
	gasMap["TableGrow"] = value
	gasMap["TableSize"] = value
	gasMap["Wake"] = value
	gasMap["I32Wait"] = value
	gasMap["I64Wait"] = value
	gasMap["Fence"] = value
	gasMap["I32AtomicLoad"] = value
	gasMap["I64AtomicLoad"] = value
	gasMap["I32AtomicLoad8U"] = value
	gasMap["I32AtomicLoad16U"] = value
	gasMap["I64AtomicLoad8U"] = value
	gasMap["I64AtomicLoad16U"] = value
	gasMap["I64AtomicLoad32U"] = value
	gasMap["I32AtomicStore"] = value
	gasMap["I64AtomicStore"] = value
	gasMap["I32AtomicStore8"] = value
	gasMap["I32AtomicStore16"] = value
	gasMap["I64AtomicStore8"] = value
	gasMap["I64AtomicStore16"] = value
	gasMap["I64AtomicStore32"] = value
	gasMap["I32AtomicRmwAdd"] = value
	gasMap["I64AtomicRmwAdd"] = value
	gasMap["I32AtomicRmw8UAdd"] = value
	gasMap["I32AtomicRmw16UAdd"] = value
	gasMap["I64AtomicRmw8UAdd"] = value
	gasMap["I64AtomicRmw16UAdd"] = value
	gasMap["I64AtomicRmw32UAdd"] = value
	gasMap["I32AtomicRmwSub"] = value
	gasMap["I64AtomicRmwSub"] = value
	gasMap["I32AtomicRmw8USub"] = value
	gasMap["I32AtomicRmw16USub"] = value
	gasMap["I64AtomicRmw8USub"] = value
	gasMap["I64AtomicRmw16USub"] = value
	gasMap["I64AtomicRmw32USub"] = value
	gasMap["I32AtomicRmwAnd"] = value
	gasMap["I64AtomicRmwAnd"] = value
	gasMap["I32AtomicRmw8UAnd"] = value
	gasMap["I32AtomicRmw16UAnd"] = value
	gasMap["I64AtomicRmw8UAnd"] = value
	gasMap["I64AtomicRmw16UAnd"] = value
	gasMap["I64AtomicRmw32UAnd"] = value
	gasMap["I32AtomicRmwOr"] = value
	gasMap["I64AtomicRmwOr"] = value
	gasMap["I32AtomicRmw8UOr"] = value
	gasMap["I32AtomicRmw16UOr"] = value
	gasMap["I64AtomicRmw8UOr"] = value
	gasMap["I64AtomicRmw16UOr"] = value
	gasMap["I64AtomicRmw32UOr"] = value
	gasMap["I32AtomicRmwXor"] = value
	gasMap["I64AtomicRmwXor"] = value
	gasMap["I32AtomicRmw8UXor"] = value
	gasMap["I32AtomicRmw16UXor"] = value
	gasMap["I64AtomicRmw8UXor"] = value
	gasMap["I64AtomicRmw16UXor"] = value
	gasMap["I64AtomicRmw32UXor"] = value
	gasMap["I32AtomicRmwXchg"] = value
	gasMap["I64AtomicRmwXchg"] = value
	gasMap["I32AtomicRmw8UXchg"] = value
	gasMap["I32AtomicRmw16UXchg"] = value
	gasMap["I64AtomicRmw8UXchg"] = value
	gasMap["I64AtomicRmw16UXchg"] = value
	gasMap["I64AtomicRmw32UXchg"] = value
	gasMap["I32AtomicRmwCmpxchg"] = value
	gasMap["I64AtomicRmwCmpxchg"] = value
	gasMap["I32AtomicRmw8UCmpxchg"] = value
	gasMap["I32AtomicRmw16UCmpxchg"] = value
	gasMap["I64AtomicRmw8UCmpxchg"] = value
	gasMap["I64AtomicRmw16UCmpxchg"] = value
	gasMap["I64AtomicRmw32UCmpxchg"] = value
	gasMap["V128Load"] = value
	gasMap["V128Store"] = value
	gasMap["V128Const"] = value
	gasMap["I8x16Splat"] = value
	gasMap["I8x16ExtractLaneS"] = value
	gasMap["I8x16ExtractLaneU"] = value
	gasMap["I8x16ReplaceLane"] = value
	gasMap["I16x8Splat"] = value
	gasMap["I16x8ExtractLaneS"] = value
	gasMap["I16x8ExtractLaneU"] = value
	gasMap["I16x8ReplaceLane"] = value
	gasMap["I32x4Splat"] = value
	gasMap["I32x4ExtractLane"] = value
	gasMap["I32x4ReplaceLane"] = value
	gasMap["I64x2Splat"] = value
	gasMap["I64x2ExtractLane"] = value
	gasMap["I64x2ReplaceLane"] = value
	gasMap["F32x4Splat"] = value
	gasMap["F32x4ExtractLane"] = value
	gasMap["F32x4ReplaceLane"] = value
	gasMap["F64x2Splat"] = value
	gasMap["F64x2ExtractLane"] = value
	gasMap["F64x2ReplaceLane"] = value
	gasMap["I8x16Eq"] = value
	gasMap["I8x16Ne"] = value
	gasMap["I8x16LtS"] = value
	gasMap["I8x16LtU"] = value
	gasMap["I8x16GtS"] = value
	gasMap["I8x16GtU"] = value
	gasMap["I8x16LeS"] = value
	gasMap["I8x16LeU"] = value
	gasMap["I8x16GeS"] = value
	gasMap["I8x16GeU"] = value
	gasMap["I16x8Eq"] = value
	gasMap["I16x8Ne"] = value
	gasMap["I16x8LtS"] = value
	gasMap["I16x8LtU"] = value
	gasMap["I16x8GtS"] = value
	gasMap["I16x8GtU"] = value
	gasMap["I16x8LeS"] = value
	gasMap["I16x8LeU"] = value
	gasMap["I16x8GeS"] = value
	gasMap["I16x8GeU"] = value
	gasMap["I32x4Eq"] = value
	gasMap["I32x4Ne"] = value
	gasMap["I32x4LtS"] = value
	gasMap["I32x4LtU"] = value
	gasMap["I32x4GtS"] = value
	gasMap["I32x4GtU"] = value
	gasMap["I32x4LeS"] = value
	gasMap["I32x4LeU"] = value
	gasMap["I32x4GeS"] = value
	gasMap["I32x4GeU"] = value
	gasMap["F32x4Eq"] = value
	gasMap["F32x4Ne"] = value
	gasMap["F32x4Lt"] = value
	gasMap["F32x4Gt"] = value
	gasMap["F32x4Le"] = value
	gasMap["F32x4Ge"] = value
	gasMap["F64x2Eq"] = value
	gasMap["F64x2Ne"] = value
	gasMap["F64x2Lt"] = value
	gasMap["F64x2Gt"] = value
	gasMap["F64x2Le"] = value
	gasMap["F64x2Ge"] = value
	gasMap["V128Not"] = value
	gasMap["V128And"] = value
	gasMap["V128Or"] = value
	gasMap["V128Xor"] = value
	gasMap["V128Bitselect"] = value
	gasMap["I8x16Neg"] = value
	gasMap["I8x16AnyTrue"] = value
	gasMap["I8x16AllTrue"] = value
	gasMap["I8x16Shl"] = value
	gasMap["I8x16ShrS"] = value
	gasMap["I8x16ShrU"] = value
	gasMap["I8x16Add"] = value
	gasMap["I8x16AddSaturateS"] = value
	gasMap["I8x16AddSaturateU"] = value
	gasMap["I8x16Sub"] = value
	gasMap["I8x16SubSaturateS"] = value
	gasMap["I8x16SubSaturateU"] = value
	gasMap["I8x16Mul"] = value
	gasMap["I16x8Neg"] = value
	gasMap["I16x8AnyTrue"] = value
	gasMap["I16x8AllTrue"] = value
	gasMap["I16x8Shl"] = value
	gasMap["I16x8ShrS"] = value
	gasMap["I16x8ShrU"] = value
	gasMap["I16x8Add"] = value
	gasMap["I16x8AddSaturateS"] = value
	gasMap["I16x8AddSaturateU"] = value
	gasMap["I16x8Sub"] = value
	gasMap["I16x8SubSaturateS"] = value
	gasMap["I16x8SubSaturateU"] = value
	gasMap["I16x8Mul"] = value
	gasMap["I32x4Neg"] = value
	gasMap["I32x4AnyTrue"] = value
	gasMap["I32x4AllTrue"] = value
	gasMap["I32x4Shl"] = value
	gasMap["I32x4ShrS"] = value
	gasMap["I32x4ShrU"] = value
	gasMap["I32x4Add"] = value
	gasMap["I32x4Sub"] = value
	gasMap["I32x4Mul"] = value
	gasMap["I64x2Neg"] = value
	gasMap["I64x2AnyTrue"] = value
	gasMap["I64x2AllTrue"] = value
	gasMap["I64x2Shl"] = value
	gasMap["I64x2ShrS"] = value
	gasMap["I64x2ShrU"] = value
	gasMap["I64x2Add"] = value
	gasMap["I64x2Sub"] = value
	gasMap["F32x4Abs"] = value
	gasMap["F32x4Neg"] = value
	gasMap["F32x4Sqrt"] = value
	gasMap["F32x4Add"] = value
	gasMap["F32x4Sub"] = value
	gasMap["F32x4Mul"] = value
	gasMap["F32x4Div"] = value
	gasMap["F32x4Min"] = value
	gasMap["F32x4Max"] = value
	gasMap["F64x2Abs"] = value
	gasMap["F64x2Neg"] = value
	gasMap["F64x2Sqrt"] = value
	gasMap["F64x2Add"] = value
	gasMap["F64x2Sub"] = value
	gasMap["F64x2Mul"] = value
	gasMap["F64x2Div"] = value
	gasMap["F64x2Min"] = value
	gasMap["F64x2Max"] = value
	gasMap["I32x4TruncSF32x4Sat"] = value
	gasMap["I32x4TruncUF32x4Sat"] = value
	gasMap["I64x2TruncSF64x2Sat"] = value
	gasMap["I64x2TruncUF64x2Sat"] = value
	gasMap["F32x4ConvertSI32x4"] = value
	gasMap["F32x4ConvertUI32x4"] = value
	gasMap["F64x2ConvertSI64x2"] = value
	gasMap["F64x2ConvertUI64x2"] = value
	gasMap["V8x16Swizzle"] = value
	gasMap["V8x16Shuffle"] = value
	gasMap["I8x16LoadSplat"] = value
	gasMap["I16x8LoadSplat"] = value
	gasMap["I32x4LoadSplat"] = value
	gasMap["I64x2LoadSplat"] = value

	return gasMap
}

func gasMapToWASMOpcodeCostsArray(gasMap map[string]uint64) [wasmer.OPCODE_COUNT]uint32 {
	opcode_costs := [wasmer.OPCODE_COUNT]uint32{}

opcode_costs[wasmer.OpcodeUnreachable] = gasMap[																		Unreachable
opcode_costs[wasmer.OpcodeNop] = gasMap[																		        Nop
opcode_costs[wasmer.OpcodeBlock] = gasMap[																		      Block
opcode_costs[wasmer.OpcodeLoop] = gasMap[																		        Loop
opcode_costs[wasmer.OpcodeIf] = gasMap[																		          If
opcode_costs[wasmer.OpcodeElse] = gasMap[																		        Else
opcode_costs[wasmer.OpcodeEnd] = gasMap[																		        End
opcode_costs[wasmer.OpcodeBr] = gasMap[																		          Br
opcode_costs[wasmer.OpcodeBrIf] = gasMap[																		        BrIf
opcode_costs[wasmer.OpcodeBrTable] = gasMap[																		    BrTable
opcode_costs[wasmer.OpcodeReturn] = gasMap[																		      Return
opcode_costs[wasmer.OpcodeCall] = gasMap[																		        Call
opcode_costs[wasmer.OpcodeCallIndirect] = gasMap[																		CallIndirect
opcode_costs[wasmer.OpcodeDrop] = gasMap[																		        Drop
opcode_costs[wasmer.OpcodeSelect] = gasMap[																		      Select
opcode_costs[wasmer.OpcodeGetLocal] = gasMap[																		    GetLocal
opcode_costs[wasmer.OpcodeSetLocal] = gasMap[																		    SetLocal
opcode_costs[wasmer.OpcodeTeeLocal] = gasMap[																		    TeeLocal
opcode_costs[wasmer.OpcodeGetGlobal] = gasMap[																		  GetGlobal
opcode_costs[wasmer.OpcodeSetGlobal] = gasMap[																		  SetGlobal
opcode_costs[wasmer.OpcodeI32Load] = gasMap[																		    I32Load
opcode_costs[wasmer.OpcodeI64Load] = gasMap[																		    I64Load
opcode_costs[wasmer.OpcodeF32Load] = gasMap[																		    F32Load
opcode_costs[wasmer.OpcodeF64Load] = gasMap[																		    F64Load
opcode_costs[wasmer.OpcodeI32Load8S] = gasMap[																		  I32Load8S
opcode_costs[wasmer.OpcodeI32Load8U] = gasMap[																		  I32Load8U
opcode_costs[wasmer.OpcodeI32Load16S] = gasMap[																		  I32Load16S
opcode_costs[wasmer.OpcodeI32Load16U] = gasMap[																		  I32Load16U
opcode_costs[wasmer.OpcodeI64Load8S] = gasMap[																		  I64Load8S
opcode_costs[wasmer.OpcodeI64Load8U] = gasMap[																		  I64Load8U
opcode_costs[wasmer.OpcodeI64Load16S] = gasMap[																		  I64Load16S
opcode_costs[wasmer.OpcodeI64Load16U] = gasMap[																		  I64Load16U
opcode_costs[wasmer.OpcodeI64Load32S] = gasMap[																		  I64Load32S
opcode_costs[wasmer.OpcodeI64Load32U] = gasMap[																		  I64Load32U
opcode_costs[wasmer.OpcodeI32Store] = gasMap[																		    I32Store
opcode_costs[wasmer.OpcodeI64Store] = gasMap[																		    I64Store
opcode_costs[wasmer.OpcodeF32Store] = gasMap[																		    F32Store
opcode_costs[wasmer.OpcodeF64Store] = gasMap[																		    F64Store
opcode_costs[wasmer.OpcodeI32Store8] = gasMap[																		  I32Store8
opcode_costs[wasmer.OpcodeI32Store16] = gasMap[																		  I32Store16
opcode_costs[wasmer.OpcodeI64Store8] = gasMap[																		  I64Store8
opcode_costs[wasmer.OpcodeI64Store16] = gasMap[																		  I64Store16
opcode_costs[wasmer.OpcodeI64Store32] = gasMap[																		  I64Store32
opcode_costs[wasmer.OpcodeMemorySize] = gasMap[																		  MemorySize
opcode_costs[wasmer.OpcodeMemoryGrow] = gasMap[																		  MemoryGrow
opcode_costs[wasmer.OpcodeI32Const] = gasMap[																		    I32Const
opcode_costs[wasmer.OpcodeI64Const] = gasMap[																		    I64Const
opcode_costs[wasmer.OpcodeF32Const] = gasMap[																		    F32Const
opcode_costs[wasmer.OpcodeF64Const] = gasMap[																		    F64Const
opcode_costs[wasmer.OpcodeRefNull] = gasMap[																		    RefNull
opcode_costs[wasmer.OpcodeRefIsNull] = gasMap[																		  RefIsNull
opcode_costs[wasmer.OpcodeI32Eqz] = gasMap[																		      I32Eqz
opcode_costs[wasmer.OpcodeI32Eq] = gasMap[																		      I32Eq
opcode_costs[wasmer.OpcodeI32Ne] = gasMap[																		      I32Ne
opcode_costs[wasmer.OpcodeI32LtS] = gasMap[																		      I32LtS
opcode_costs[wasmer.OpcodeI32LtU] = gasMap[																		      I32LtU
opcode_costs[wasmer.OpcodeI32GtS] = gasMap[																		      I32GtS
opcode_costs[wasmer.OpcodeI32GtU] = gasMap[																		      I32GtU
opcode_costs[wasmer.OpcodeI32LeS] = gasMap[																		      I32LeS
opcode_costs[wasmer.OpcodeI32LeU] = gasMap[																		      I32LeU
opcode_costs[wasmer.OpcodeI32GeS] = gasMap[																		      I32GeS
opcode_costs[wasmer.OpcodeI32GeU] = gasMap[																		      I32GeU
opcode_costs[wasmer.OpcodeI64Eqz] = gasMap[																		      I64Eqz
opcode_costs[wasmer.OpcodeI64Eq] = gasMap[																		      I64Eq
opcode_costs[wasmer.OpcodeI64Ne] = gasMap[																		      I64Ne
opcode_costs[wasmer.OpcodeI64LtS] = gasMap[																		      I64LtS
opcode_costs[wasmer.OpcodeI64LtU] = gasMap[																		      I64LtU
opcode_costs[wasmer.OpcodeI64GtS] = gasMap[																		      I64GtS
opcode_costs[wasmer.OpcodeI64GtU] = gasMap[																		      I64GtU
opcode_costs[wasmer.OpcodeI64LeS] = gasMap[																		      I64LeS
opcode_costs[wasmer.OpcodeI64LeU] = gasMap[																		      I64LeU
opcode_costs[wasmer.OpcodeI64GeS] = gasMap[																		      I64GeS
opcode_costs[wasmer.OpcodeI64GeU] = gasMap[																		      I64GeU
opcode_costs[wasmer.OpcodeF32Eq] = gasMap[																		      F32Eq
opcode_costs[wasmer.OpcodeF32Ne] = gasMap[																		      F32Ne
opcode_costs[wasmer.OpcodeF32Lt] = gasMap[																		      F32Lt
opcode_costs[wasmer.OpcodeF32Gt] = gasMap[																		      F32Gt
opcode_costs[wasmer.OpcodeF32Le] = gasMap[																		      F32Le
opcode_costs[wasmer.OpcodeF32Ge] = gasMap[																		      F32Ge
opcode_costs[wasmer.OpcodeF64Eq] = gasMap[																		      F64Eq
opcode_costs[wasmer.OpcodeF64Ne] = gasMap[																		      F64Ne
opcode_costs[wasmer.OpcodeF64Lt] = gasMap[																		      F64Lt
opcode_costs[wasmer.OpcodeF64Gt] = gasMap[																		      F64Gt
opcode_costs[wasmer.OpcodeF64Le] = gasMap[																		      F64Le
opcode_costs[wasmer.OpcodeF64Ge] = gasMap[																		      F64Ge
opcode_costs[wasmer.OpcodeI32Clz] = gasMap[																		      I32Clz
opcode_costs[wasmer.OpcodeI32Ctz] = gasMap[																		      I32Ctz
opcode_costs[wasmer.OpcodeI32Popcnt] = gasMap[																		  I32Popcnt
opcode_costs[wasmer.OpcodeI32Add] = gasMap[																		      I32Add
opcode_costs[wasmer.OpcodeI32Sub] = gasMap[																		      I32Sub
opcode_costs[wasmer.OpcodeI32Mul] = gasMap[																		      I32Mul
opcode_costs[wasmer.OpcodeI32DivS] = gasMap[																		    I32DivS
opcode_costs[wasmer.OpcodeI32DivU] = gasMap[																		    I32DivU
opcode_costs[wasmer.OpcodeI32RemS] = gasMap[																		    I32RemS
opcode_costs[wasmer.OpcodeI32RemU] = gasMap[																		    I32RemU
opcode_costs[wasmer.OpcodeI32And] = gasMap[																		      I32And
opcode_costs[wasmer.OpcodeI32Or] = gasMap[																		      I32Or
opcode_costs[wasmer.OpcodeI32Xor] = gasMap[																		      I32Xor
opcode_costs[wasmer.OpcodeI32Shl] = gasMap[																		      I32Shl
opcode_costs[wasmer.OpcodeI32ShrS] = gasMap[																		    I32ShrS
opcode_costs[wasmer.OpcodeI32ShrU] = gasMap[																		    I32ShrU
opcode_costs[wasmer.OpcodeI32Rotl] = gasMap[																		    I32Rotl
opcode_costs[wasmer.OpcodeI32Rotr] = gasMap[																		    I32Rotr
opcode_costs[wasmer.OpcodeI64Clz] = gasMap[																		      I64Clz
opcode_costs[wasmer.OpcodeI64Ctz] = gasMap[																		      I64Ctz
opcode_costs[wasmer.OpcodeI64Popcnt] = gasMap[																		  I64Popcnt
opcode_costs[wasmer.OpcodeI64Add] = gasMap[																		      I64Add
opcode_costs[wasmer.OpcodeI64Sub] = gasMap[																		      I64Sub
opcode_costs[wasmer.OpcodeI64Mul] = gasMap[																		      I64Mul
opcode_costs[wasmer.OpcodeI64DivS] = gasMap[																		    I64DivS
opcode_costs[wasmer.OpcodeI64DivU] = gasMap[																		    I64DivU
opcode_costs[wasmer.OpcodeI64RemS] = gasMap[																		    I64RemS
opcode_costs[wasmer.OpcodeI64RemU] = gasMap[																		    I64RemU
opcode_costs[wasmer.OpcodeI64And] = gasMap[																		      I64And
opcode_costs[wasmer.OpcodeI64Or] = gasMap[																		      I64Or
opcode_costs[wasmer.OpcodeI64Xor] = gasMap[																		      I64Xor
opcode_costs[wasmer.OpcodeI64Shl] = gasMap[																		      I64Shl
opcode_costs[wasmer.OpcodeI64ShrS] = gasMap[																		    I64ShrS
opcode_costs[wasmer.OpcodeI64ShrU] = gasMap[																		    I64ShrU
opcode_costs[wasmer.OpcodeI64Rotl] = gasMap[																		    I64Rotl
opcode_costs[wasmer.OpcodeI64Rotr] = gasMap[																		    I64Rotr
opcode_costs[wasmer.OpcodeF32Abs] = gasMap[																		      F32Abs
opcode_costs[wasmer.OpcodeF32Neg] = gasMap[																		      F32Neg
opcode_costs[wasmer.OpcodeF32Ceil] = gasMap[																		    F32Ceil
opcode_costs[wasmer.OpcodeF32Floor] = gasMap[																		    F32Floor
opcode_costs[wasmer.OpcodeF32Trunc] = gasMap[																		    F32Trunc
opcode_costs[wasmer.OpcodeF32Nearest] = gasMap[																		  F32Nearest
opcode_costs[wasmer.OpcodeF32Sqrt] = gasMap[																		    F32Sqrt
opcode_costs[wasmer.OpcodeF32Add] = gasMap[																		      F32Add
opcode_costs[wasmer.OpcodeF32Sub] = gasMap[																		      F32Sub
opcode_costs[wasmer.OpcodeF32Mul] = gasMap[																		      F32Mul
opcode_costs[wasmer.OpcodeF32Div] = gasMap[																		      F32Div
opcode_costs[wasmer.OpcodeF32Min] = gasMap[																		      F32Min
opcode_costs[wasmer.OpcodeF32Max] = gasMap[																		      F32Max
opcode_costs[wasmer.OpcodeF32Copysign] = gasMap[																		F32Copysign
opcode_costs[wasmer.OpcodeF64Abs] = gasMap[																		      F64Abs
opcode_costs[wasmer.OpcodeF64Neg] = gasMap[																		      F64Neg
opcode_costs[wasmer.OpcodeF64Ceil] = gasMap[																		    F64Ceil
opcode_costs[wasmer.OpcodeF64Floor] = gasMap[																		    F64Floor
opcode_costs[wasmer.OpcodeF64Trunc] = gasMap[																		    F64Trunc
opcode_costs[wasmer.OpcodeF64Nearest] = gasMap[																		  F64Nearest
opcode_costs[wasmer.OpcodeF64Sqrt] = gasMap[																		    F64Sqrt
opcode_costs[wasmer.OpcodeF64Add] = gasMap[																		      F64Add
opcode_costs[wasmer.OpcodeF64Sub] = gasMap[																		      F64Sub
opcode_costs[wasmer.OpcodeF64Mul] = gasMap[																		      F64Mul
opcode_costs[wasmer.OpcodeF64Div] = gasMap[																		      F64Div
opcode_costs[wasmer.OpcodeF64Min] = gasMap[																		      F64Min
opcode_costs[wasmer.OpcodeF64Max] = gasMap[																		      F64Max
opcode_costs[wasmer.OpcodeF64Copysign] = gasMap[																		F64Copysign
opcode_costs[wasmer.OpcodeI32WrapI64] = gasMap[																		  I32WrapI64
opcode_costs[wasmer.OpcodeI32TruncSF32] = gasMap[																		I32TruncSF32
opcode_costs[wasmer.OpcodeI32TruncUF32] = gasMap[																		I32TruncUF32
opcode_costs[wasmer.OpcodeI32TruncSF64] = gasMap[																		I32TruncSF64
opcode_costs[wasmer.OpcodeI32TruncUF64] = gasMap[																		I32TruncUF64
opcode_costs[wasmer.OpcodeI64ExtendSI32] = gasMap[																	I64ExtendSI32         	
opcode_costs[wasmer.OpcodeI64ExtendUI32] = gasMap[																	I64ExtendUI32         	
opcode_costs[wasmer.OpcodeI64TruncSF32] = gasMap[																		I64TruncSF32
opcode_costs[wasmer.OpcodeI64TruncUF32] = gasMap[																		I64TruncUF32
opcode_costs[wasmer.OpcodeI64TruncSF64] = gasMap[																		I64TruncSF64
opcode_costs[wasmer.OpcodeI64TruncUF64] = gasMap[																		I64TruncUF64
opcode_costs[wasmer.OpcodeF32ConvertSI32] = gasMap[																	F32ConvertSI32        	
opcode_costs[wasmer.OpcodeF32ConvertUI32] = gasMap[																	F32ConvertUI32        	
opcode_costs[wasmer.OpcodeF32ConvertSI64] = gasMap[																	F32ConvertSI64        	
opcode_costs[wasmer.OpcodeF32ConvertUI64] = gasMap[																	F32ConvertUI64        	
opcode_costs[wasmer.OpcodeF32DemoteF64] = gasMap[																		F32DemoteF64
opcode_costs[wasmer.OpcodeF64ConvertSI32] = gasMap[																	F64ConvertSI32        	
opcode_costs[wasmer.OpcodeF64ConvertUI32] = gasMap[																	F64ConvertUI32        	
opcode_costs[wasmer.OpcodeF64ConvertSI64] = gasMap[																	F64ConvertSI64        	
opcode_costs[wasmer.OpcodeF64ConvertUI64] = gasMap[																	F64ConvertUI64        	
opcode_costs[wasmer.OpcodeF64PromoteF32] = gasMap[																	F64PromoteF32         	
opcode_costs[wasmer.OpcodeI32ReinterpretF32] = gasMap[															I32ReinterpretF32     			
opcode_costs[wasmer.OpcodeI64ReinterpretF64] = gasMap[															I64ReinterpretF64     			
opcode_costs[wasmer.OpcodeF32ReinterpretI32] = gasMap[															F32ReinterpretI32     			
opcode_costs[wasmer.OpcodeF64ReinterpretI64] = gasMap[															F64ReinterpretI64     			
opcode_costs[wasmer.OpcodeI32Extend8S] = gasMap[																		I32Extend8S
opcode_costs[wasmer.OpcodeI32Extend16S] = gasMap[																		I32Extend16S
opcode_costs[wasmer.OpcodeI64Extend8S] = gasMap[																		I64Extend8S
opcode_costs[wasmer.OpcodeI64Extend16S] = gasMap[																		I64Extend16S
opcode_costs[wasmer.OpcodeI64Extend32S] = gasMap[																		I64Extend32S
opcode_costs[wasmer.OpcodeI32TruncSSatF32] = gasMap[																I32TruncSSatF32       		
opcode_costs[wasmer.OpcodeI32TruncUSatF32] = gasMap[																I32TruncUSatF32       		
opcode_costs[wasmer.OpcodeI32TruncSSatF64] = gasMap[																I32TruncSSatF64       		
opcode_costs[wasmer.OpcodeI32TruncUSatF64] = gasMap[																I32TruncUSatF64       		
opcode_costs[wasmer.OpcodeI64TruncSSatF32] = gasMap[																I64TruncSSatF32       		
opcode_costs[wasmer.OpcodeI64TruncUSatF32] = gasMap[																I64TruncUSatF32       		
opcode_costs[wasmer.OpcodeI64TruncSSatF64] = gasMap[																I64TruncSSatF64       		
opcode_costs[wasmer.OpcodeI64TruncUSatF64] = gasMap[																I64TruncUSatF64       		
opcode_costs[wasmer.OpcodeMemoryInit] = gasMap[																		  MemoryInit
opcode_costs[wasmer.OpcodeDataDrop] = gasMap[																		    DataDrop
opcode_costs[wasmer.OpcodeMemoryCopy] = gasMap[																		  MemoryCopy
opcode_costs[wasmer.OpcodeMemoryFill] = gasMap[																		  MemoryFill
opcode_costs[wasmer.OpcodeTableInit] = gasMap[																		  TableInit
opcode_costs[wasmer.OpcodeElemDrop] = gasMap[																		    ElemDrop
opcode_costs[wasmer.OpcodeTableCopy] = gasMap[																		  TableCopy
opcode_costs[wasmer.OpcodeTableGet] = gasMap[																		    TableGet
opcode_costs[wasmer.OpcodeTableSet] = gasMap[																		    TableSet
opcode_costs[wasmer.OpcodeTableGrow] = gasMap[																		  TableGrow
opcode_costs[wasmer.OpcodeTableSize] = gasMap[																		  TableSize
opcode_costs[wasmer.OpcodeWake] = gasMap[																		        Wake
opcode_costs[wasmer.OpcodeI32Wait] = gasMap[																		    I32Wait
opcode_costs[wasmer.OpcodeI64Wait] = gasMap[																		    I64Wait
opcode_costs[wasmer.OpcodeFence] = gasMap[																		      Fence
opcode_costs[wasmer.OpcodeI32AtomicLoad] = gasMap[																	I32AtomicLoad         	
opcode_costs[wasmer.OpcodeI64AtomicLoad] = gasMap[																	I64AtomicLoad         	
opcode_costs[wasmer.OpcodeI32AtomicLoad8U] = gasMap[																I32AtomicLoad8U       		
opcode_costs[wasmer.OpcodeI32AtomicLoad16U] = gasMap[																I32AtomicLoad16U      		
opcode_costs[wasmer.OpcodeI64AtomicLoad8U] = gasMap[																I64AtomicLoad8U       		
opcode_costs[wasmer.OpcodeI64AtomicLoad16U] = gasMap[																I64AtomicLoad16U      		
opcode_costs[wasmer.OpcodeI64AtomicLoad32U] = gasMap[																I64AtomicLoad32U      		
opcode_costs[wasmer.OpcodeI32AtomicStore] = gasMap[																	I32AtomicStore        	
opcode_costs[wasmer.OpcodeI64AtomicStore] = gasMap[																	I64AtomicStore        	
opcode_costs[wasmer.OpcodeI32AtomicStore8] = gasMap[																I32AtomicStore8       		
opcode_costs[wasmer.OpcodeI32AtomicStore16] = gasMap[																I32AtomicStore16      		
opcode_costs[wasmer.OpcodeI64AtomicStore8] = gasMap[																I64AtomicStore8       		
opcode_costs[wasmer.OpcodeI64AtomicStore16] = gasMap[																I64AtomicStore16      		
opcode_costs[wasmer.OpcodeI64AtomicStore32] = gasMap[																I64AtomicStore32      		
opcode_costs[wasmer.OpcodeI32AtomicRmwAdd] = gasMap[																I32AtomicRmwAdd       		
opcode_costs[wasmer.OpcodeI64AtomicRmwAdd] = gasMap[																I64AtomicRmwAdd       		
opcode_costs[wasmer.OpcodeI32AtomicRmw8UAdd] = gasMap[															I32AtomicRmw8UAdd     			
opcode_costs[wasmer.OpcodeI32AtomicRmw16UAdd] = gasMap[															I32AtomicRmw16UAdd    			
opcode_costs[wasmer.OpcodeI64AtomicRmw8UAdd] = gasMap[															I64AtomicRmw8UAdd     			
opcode_costs[wasmer.OpcodeI64AtomicRmw16UAdd] = gasMap[															I64AtomicRmw16UAdd    			
opcode_costs[wasmer.OpcodeI64AtomicRmw32UAdd] = gasMap[															I64AtomicRmw32UAdd    			
opcode_costs[wasmer.OpcodeI32AtomicRmwSub] = gasMap[																I32AtomicRmwSub       		
opcode_costs[wasmer.OpcodeI64AtomicRmwSub] = gasMap[																I64AtomicRmwSub       		
opcode_costs[wasmer.OpcodeI32AtomicRmw8USub] = gasMap[															I32AtomicRmw8USub     			
opcode_costs[wasmer.OpcodeI32AtomicRmw16USub] = gasMap[															I32AtomicRmw16USub    			
opcode_costs[wasmer.OpcodeI64AtomicRmw8USub] = gasMap[															I64AtomicRmw8USub     			
opcode_costs[wasmer.OpcodeI64AtomicRmw16USub] = gasMap[															I64AtomicRmw16USub    			
opcode_costs[wasmer.OpcodeI64AtomicRmw32USub] = gasMap[															I64AtomicRmw32USub    			
opcode_costs[wasmer.OpcodeI32AtomicRmwAnd] = gasMap[																I32AtomicRmwAnd       		
opcode_costs[wasmer.OpcodeI64AtomicRmwAnd] = gasMap[																I64AtomicRmwAnd       		
opcode_costs[wasmer.OpcodeI32AtomicRmw8UAnd] = gasMap[															I32AtomicRmw8UAnd     			
opcode_costs[wasmer.OpcodeI32AtomicRmw16UAnd] = gasMap[															I32AtomicRmw16UAnd    			
opcode_costs[wasmer.OpcodeI64AtomicRmw8UAnd] = gasMap[															I64AtomicRmw8UAnd     			
opcode_costs[wasmer.OpcodeI64AtomicRmw16UAnd] = gasMap[															I64AtomicRmw16UAnd    			
opcode_costs[wasmer.OpcodeI64AtomicRmw32UAnd] = gasMap[															I64AtomicRmw32UAnd    			
opcode_costs[wasmer.OpcodeI32AtomicRmwOr] = gasMap[																	I32AtomicRmwOr        	
opcode_costs[wasmer.OpcodeI64AtomicRmwOr] = gasMap[																	I64AtomicRmwOr        	
opcode_costs[wasmer.OpcodeI32AtomicRmw8UOr] = gasMap[																I32AtomicRmw8UOr      		
opcode_costs[wasmer.OpcodeI32AtomicRmw16UOr] = gasMap[															I32AtomicRmw16UOr     			
opcode_costs[wasmer.OpcodeI64AtomicRmw8UOr] = gasMap[																I64AtomicRmw8UOr      		
opcode_costs[wasmer.OpcodeI64AtomicRmw16UOr] = gasMap[															I64AtomicRmw16UOr     			
opcode_costs[wasmer.OpcodeI64AtomicRmw32UOr] = gasMap[															I64AtomicRmw32UOr     			
opcode_costs[wasmer.OpcodeI32AtomicRmwXor] = gasMap[																I32AtomicRmwXor       		
opcode_costs[wasmer.OpcodeI64AtomicRmwXor] = gasMap[																I64AtomicRmwXor       		
opcode_costs[wasmer.OpcodeI32AtomicRmw8UXor] = gasMap[															I32AtomicRmw8UXor     			
opcode_costs[wasmer.OpcodeI32AtomicRmw16UXor] = gasMap[															I32AtomicRmw16UXor    			
opcode_costs[wasmer.OpcodeI64AtomicRmw8UXor] = gasMap[															I64AtomicRmw8UXor     			
opcode_costs[wasmer.OpcodeI64AtomicRmw16UXor] = gasMap[															I64AtomicRmw16UXor    			
opcode_costs[wasmer.OpcodeI64AtomicRmw32UXor] = gasMap[															I64AtomicRmw32UXor    			
opcode_costs[wasmer.OpcodeI32AtomicRmwXchg] = gasMap[																I32AtomicRmwXchg      		
opcode_costs[wasmer.OpcodeI64AtomicRmwXchg] = gasMap[																I64AtomicRmwXchg      		
opcode_costs[wasmer.OpcodeI32AtomicRmw8UXchg] = gasMap[															I32AtomicRmw8UXchg    			
opcode_costs[wasmer.OpcodeI32AtomicRmw16UXchg] = gasMap[														I32AtomicRmw16UXchg   				
opcode_costs[wasmer.OpcodeI64AtomicRmw8UXchg] = gasMap[															I64AtomicRmw8UXchg    			
opcode_costs[wasmer.OpcodeI64AtomicRmw16UXchg] = gasMap[														I64AtomicRmw16UXchg   				
opcode_costs[wasmer.OpcodeI64AtomicRmw32UXchg] = gasMap[														I64AtomicRmw32UXchg   				
opcode_costs[wasmer.OpcodeI32AtomicRmwCmpxchg] = gasMap[														I32AtomicRmwCmpxchg   				
opcode_costs[wasmer.OpcodeI64AtomicRmwCmpxchg] = gasMap[														I64AtomicRmwCmpxchg   				
opcode_costs[wasmer.OpcodeI32AtomicRmw8UCmpxchg] = gasMap[													I32AtomicRmw8UCmpxchg 					
opcode_costs[wasmer.OpcodeI32AtomicRmw16UCmpxchg] = gasMap[													I32AtomicRmw16UCmpxchg					
opcode_costs[wasmer.OpcodeI64AtomicRmw8UCmpxchg] = gasMap[													I64AtomicRmw8UCmpxchg 					
opcode_costs[wasmer.OpcodeI64AtomicRmw16UCmpxchg] = gasMap[													I64AtomicRmw16UCmpxchg					
opcode_costs[wasmer.OpcodeI64AtomicRmw32UCmpxchg] = gasMap[													I64AtomicRmw32UCmpxchg					
opcode_costs[wasmer.OpcodeV128Load] = gasMap[																		    V128Load
opcode_costs[wasmer.OpcodeV128Store] = gasMap[																		  V128Store
opcode_costs[wasmer.OpcodeV128Const] = gasMap[																		  V128Const
opcode_costs[wasmer.OpcodeI8x16Splat] = gasMap[																		  I8x16Splat
opcode_costs[wasmer.OpcodeI8x16ExtractLaneS] = gasMap[															I8x16ExtractLaneS     			
opcode_costs[wasmer.OpcodeI8x16ExtractLaneU] = gasMap[															I8x16ExtractLaneU     			
opcode_costs[wasmer.OpcodeI8x16ReplaceLane] = gasMap[																I8x16ReplaceLane      		
opcode_costs[wasmer.OpcodeI16x8Splat] = gasMap[																		  I16x8Splat
opcode_costs[wasmer.OpcodeI16x8ExtractLaneS] = gasMap[															I16x8ExtractLaneS     			
opcode_costs[wasmer.OpcodeI16x8ExtractLaneU] = gasMap[															I16x8ExtractLaneU     			
opcode_costs[wasmer.OpcodeI16x8ReplaceLane] = gasMap[																I16x8ReplaceLane      		
opcode_costs[wasmer.OpcodeI32x4Splat] = gasMap[																		  I32x4Splat
opcode_costs[wasmer.OpcodeI32x4ExtractLane] = gasMap[																I32x4ExtractLane      		
opcode_costs[wasmer.OpcodeI32x4ReplaceLane] = gasMap[																I32x4ReplaceLane      		
opcode_costs[wasmer.OpcodeI64x2Splat] = gasMap[																		  I64x2Splat
opcode_costs[wasmer.OpcodeI64x2ExtractLane] = gasMap[																I64x2ExtractLane      		
opcode_costs[wasmer.OpcodeI64x2ReplaceLane] = gasMap[																I64x2ReplaceLane      		
opcode_costs[wasmer.OpcodeF32x4Splat] = gasMap[																		  F32x4Splat
opcode_costs[wasmer.OpcodeF32x4ExtractLane] = gasMap[																F32x4ExtractLane      		
opcode_costs[wasmer.OpcodeF32x4ReplaceLane] = gasMap[																F32x4ReplaceLane      		
opcode_costs[wasmer.OpcodeF64x2Splat] = gasMap[																		  F64x2Splat
opcode_costs[wasmer.OpcodeF64x2ExtractLane] = gasMap[																F64x2ExtractLane      		
opcode_costs[wasmer.OpcodeF64x2ReplaceLane] = gasMap[																F64x2ReplaceLane      		
opcode_costs[wasmer.OpcodeI8x16Eq] = gasMap[																		    I8x16Eq
opcode_costs[wasmer.OpcodeI8x16Ne] = gasMap[																		    I8x16Ne
opcode_costs[wasmer.OpcodeI8x16LtS] = gasMap[																		    I8x16LtS
opcode_costs[wasmer.OpcodeI8x16LtU] = gasMap[																		    I8x16LtU
opcode_costs[wasmer.OpcodeI8x16GtS] = gasMap[																		    I8x16GtS
opcode_costs[wasmer.OpcodeI8x16GtU] = gasMap[																		    I8x16GtU
opcode_costs[wasmer.OpcodeI8x16LeS] = gasMap[																		    I8x16LeS
opcode_costs[wasmer.OpcodeI8x16LeU] = gasMap[																		    I8x16LeU
opcode_costs[wasmer.OpcodeI8x16GeS] = gasMap[																		    I8x16GeS
opcode_costs[wasmer.OpcodeI8x16GeU] = gasMap[																		    I8x16GeU
opcode_costs[wasmer.OpcodeI16x8Eq] = gasMap[																		    I16x8Eq
opcode_costs[wasmer.OpcodeI16x8Ne] = gasMap[																		    I16x8Ne
opcode_costs[wasmer.OpcodeI16x8LtS] = gasMap[																		    I16x8LtS
opcode_costs[wasmer.OpcodeI16x8LtU] = gasMap[																		    I16x8LtU
opcode_costs[wasmer.OpcodeI16x8GtS] = gasMap[																		    I16x8GtS
opcode_costs[wasmer.OpcodeI16x8GtU] = gasMap[																		    I16x8GtU
opcode_costs[wasmer.OpcodeI16x8LeS] = gasMap[																		    I16x8LeS
opcode_costs[wasmer.OpcodeI16x8LeU] = gasMap[																		    I16x8LeU
opcode_costs[wasmer.OpcodeI16x8GeS] = gasMap[																		    I16x8GeS
opcode_costs[wasmer.OpcodeI16x8GeU] = gasMap[																		    I16x8GeU
opcode_costs[wasmer.OpcodeI32x4Eq] = gasMap[																		    I32x4Eq
opcode_costs[wasmer.OpcodeI32x4Ne] = gasMap[																		    I32x4Ne
opcode_costs[wasmer.OpcodeI32x4LtS] = gasMap[																		    I32x4LtS
opcode_costs[wasmer.OpcodeI32x4LtU] = gasMap[																		    I32x4LtU
opcode_costs[wasmer.OpcodeI32x4GtS] = gasMap[																		    I32x4GtS
opcode_costs[wasmer.OpcodeI32x4GtU] = gasMap[																		    I32x4GtU
opcode_costs[wasmer.OpcodeI32x4LeS] = gasMap[																		    I32x4LeS
opcode_costs[wasmer.OpcodeI32x4LeU] = gasMap[																		    I32x4LeU
opcode_costs[wasmer.OpcodeI32x4GeS] = gasMap[																		    I32x4GeS
opcode_costs[wasmer.OpcodeI32x4GeU] = gasMap[																		    I32x4GeU
opcode_costs[wasmer.OpcodeF32x4Eq] = gasMap[																		    F32x4Eq
opcode_costs[wasmer.OpcodeF32x4Ne] = gasMap[																		    F32x4Ne
opcode_costs[wasmer.OpcodeF32x4Lt] = gasMap[																		    F32x4Lt
opcode_costs[wasmer.OpcodeF32x4Gt] = gasMap[																		    F32x4Gt
opcode_costs[wasmer.OpcodeF32x4Le] = gasMap[																		    F32x4Le
opcode_costs[wasmer.OpcodeF32x4Ge] = gasMap[																		    F32x4Ge
opcode_costs[wasmer.OpcodeF64x2Eq] = gasMap[																		    F64x2Eq
opcode_costs[wasmer.OpcodeF64x2Ne] = gasMap[																		    F64x2Ne
opcode_costs[wasmer.OpcodeF64x2Lt] = gasMap[																		    F64x2Lt
opcode_costs[wasmer.OpcodeF64x2Gt] = gasMap[																		    F64x2Gt
opcode_costs[wasmer.OpcodeF64x2Le] = gasMap[																		    F64x2Le
opcode_costs[wasmer.OpcodeF64x2Ge] = gasMap[																		    F64x2Ge
opcode_costs[wasmer.OpcodeV128Not] = gasMap[																		    V128Not
opcode_costs[wasmer.OpcodeV128And] = gasMap[																		    V128And
opcode_costs[wasmer.OpcodeV128Or] = gasMap[																		      V128Or
opcode_costs[wasmer.OpcodeV128Xor] = gasMap[																		    V128Xor
opcode_costs[wasmer.OpcodeV128Bitselect] = gasMap[																	V128Bitselect         	
opcode_costs[wasmer.OpcodeI8x16Neg] = gasMap[																		    I8x16Neg
opcode_costs[wasmer.OpcodeI8x16AnyTrue] = gasMap[																		I8x16AnyTrue
opcode_costs[wasmer.OpcodeI8x16AllTrue] = gasMap[																		I8x16AllTrue
opcode_costs[wasmer.OpcodeI8x16Shl] = gasMap[																		    I8x16Shl
opcode_costs[wasmer.OpcodeI8x16ShrS] = gasMap[																		  I8x16ShrS
opcode_costs[wasmer.OpcodeI8x16ShrU] = gasMap[																		  I8x16ShrU
opcode_costs[wasmer.OpcodeI8x16Add] = gasMap[																		    I8x16Add
opcode_costs[wasmer.OpcodeI8x16AddSaturateS] = gasMap[															I8x16AddSaturateS     			
opcode_costs[wasmer.OpcodeI8x16AddSaturateU] = gasMap[															I8x16AddSaturateU     			
opcode_costs[wasmer.OpcodeI8x16Sub] = gasMap[																		    I8x16Sub
opcode_costs[wasmer.OpcodeI8x16SubSaturateS] = gasMap[															I8x16SubSaturateS     			
opcode_costs[wasmer.OpcodeI8x16SubSaturateU] = gasMap[															I8x16SubSaturateU     			
opcode_costs[wasmer.OpcodeI8x16Mul] = gasMap[																		    I8x16Mul
opcode_costs[wasmer.OpcodeI16x8Neg] = gasMap[																		    I16x8Neg
opcode_costs[wasmer.OpcodeI16x8AnyTrue] = gasMap[																		I16x8AnyTrue
opcode_costs[wasmer.OpcodeI16x8AllTrue] = gasMap[																		I16x8AllTrue
opcode_costs[wasmer.OpcodeI16x8Shl] = gasMap[																		    I16x8Shl
opcode_costs[wasmer.OpcodeI16x8ShrS] = gasMap[																		  I16x8ShrS
opcode_costs[wasmer.OpcodeI16x8ShrU] = gasMap[																		  I16x8ShrU
opcode_costs[wasmer.OpcodeI16x8Add] = gasMap[																		    I16x8Add
opcode_costs[wasmer.OpcodeI16x8AddSaturateS] = gasMap[															I16x8AddSaturateS     			
opcode_costs[wasmer.OpcodeI16x8AddSaturateU] = gasMap[															I16x8AddSaturateU     			
opcode_costs[wasmer.OpcodeI16x8Sub] = gasMap[																		    I16x8Sub
opcode_costs[wasmer.OpcodeI16x8SubSaturateS] = gasMap[															I16x8SubSaturateS     			
opcode_costs[wasmer.OpcodeI16x8SubSaturateU] = gasMap[															I16x8SubSaturateU     			
opcode_costs[wasmer.OpcodeI16x8Mul] = gasMap[																		    I16x8Mul
opcode_costs[wasmer.OpcodeI32x4Neg] = gasMap[																		    I32x4Neg
opcode_costs[wasmer.OpcodeI32x4AnyTrue] = gasMap[																		I32x4AnyTrue
opcode_costs[wasmer.OpcodeI32x4AllTrue] = gasMap[																		I32x4AllTrue
opcode_costs[wasmer.OpcodeI32x4Shl] = gasMap[																		    I32x4Shl
opcode_costs[wasmer.OpcodeI32x4ShrS] = gasMap[																		  I32x4ShrS
opcode_costs[wasmer.OpcodeI32x4ShrU] = gasMap[																		  I32x4ShrU
opcode_costs[wasmer.OpcodeI32x4Add] = gasMap[																		    I32x4Add
opcode_costs[wasmer.OpcodeI32x4Sub] = gasMap[																		    I32x4Sub
opcode_costs[wasmer.OpcodeI32x4Mul] = gasMap[																		    I32x4Mul
opcode_costs[wasmer.OpcodeI64x2Neg] = gasMap[																		    I64x2Neg
opcode_costs[wasmer.OpcodeI64x2AnyTrue] = gasMap[																		I64x2AnyTrue
opcode_costs[wasmer.OpcodeI64x2AllTrue] = gasMap[																		I64x2AllTrue
opcode_costs[wasmer.OpcodeI64x2Shl] = gasMap[																		    I64x2Shl
opcode_costs[wasmer.OpcodeI64x2ShrS] = gasMap[																		  I64x2ShrS
opcode_costs[wasmer.OpcodeI64x2ShrU] = gasMap[																		  I64x2ShrU
opcode_costs[wasmer.OpcodeI64x2Add] = gasMap[																		    I64x2Add
opcode_costs[wasmer.OpcodeI64x2Sub] = gasMap[																		    I64x2Sub
opcode_costs[wasmer.OpcodeF32x4Abs] = gasMap[																		    F32x4Abs
opcode_costs[wasmer.OpcodeF32x4Neg] = gasMap[																		    F32x4Neg
opcode_costs[wasmer.OpcodeF32x4Sqrt] = gasMap[																		  F32x4Sqrt
opcode_costs[wasmer.OpcodeF32x4Add] = gasMap[																		    F32x4Add
opcode_costs[wasmer.OpcodeF32x4Sub] = gasMap[																		    F32x4Sub
opcode_costs[wasmer.OpcodeF32x4Mul] = gasMap[																		    F32x4Mul
opcode_costs[wasmer.OpcodeF32x4Div] = gasMap[																		    F32x4Div
opcode_costs[wasmer.OpcodeF32x4Min] = gasMap[																		    F32x4Min
opcode_costs[wasmer.OpcodeF32x4Max] = gasMap[																		    F32x4Max
opcode_costs[wasmer.OpcodeF64x2Abs] = gasMap[																		    F64x2Abs
opcode_costs[wasmer.OpcodeF64x2Neg] = gasMap[																		    F64x2Neg
opcode_costs[wasmer.OpcodeF64x2Sqrt] = gasMap[																		  F64x2Sqrt
opcode_costs[wasmer.OpcodeF64x2Add] = gasMap[																		    F64x2Add
opcode_costs[wasmer.OpcodeF64x2Sub] = gasMap[																		    F64x2Sub
opcode_costs[wasmer.OpcodeF64x2Mul] = gasMap[																		    F64x2Mul
opcode_costs[wasmer.OpcodeF64x2Div] = gasMap[																		    F64x2Div
opcode_costs[wasmer.OpcodeF64x2Min] = gasMap[																		    F64x2Min
opcode_costs[wasmer.OpcodeF64x2Max] = gasMap[																		    F64x2Max
opcode_costs[wasmer.OpcodeI32x4TruncSF32x4Sat] = gasMap[														I32x4TruncSF32x4Sat   				
opcode_costs[wasmer.OpcodeI32x4TruncUF32x4Sat] = gasMap[														I32x4TruncUF32x4Sat   				
opcode_costs[wasmer.OpcodeI64x2TruncSF64x2Sat] = gasMap[														I64x2TruncSF64x2Sat   				
opcode_costs[wasmer.OpcodeI64x2TruncUF64x2Sat] = gasMap[														I64x2TruncUF64x2Sat   				
opcode_costs[wasmer.OpcodeF32x4ConvertSI32x4] = gasMap[															F32x4ConvertSI32x4    			
opcode_costs[wasmer.OpcodeF32x4ConvertUI32x4] = gasMap[															F32x4ConvertUI32x4    			
opcode_costs[wasmer.OpcodeF64x2ConvertSI64x2] = gasMap[															F64x2ConvertSI64x2    			
opcode_costs[wasmer.OpcodeF64x2ConvertUI64x2] = gasMap[															F64x2ConvertUI64x2    			
opcode_costs[wasmer.OpcodeV8x16Swizzle] = gasMap[																		V8x16Swizzle
opcode_costs[wasmer.OpcodeV8x16Shuffle] = gasMap[																		V8x16Shuffle
opcode_costs[wasmer.OpcodeI8x16LoadSplat] = gasMap[																	I8x16LoadSplat        	
opcode_costs[wasmer.OpcodeI16x8LoadSplat] = gasMap[																	I16x8LoadSplat        	
opcode_costs[wasmer.OpcodeI32x4LoadSplat] = gasMap[																	I32x4LoadSplat        	
opcode_costs[wasmer.OpcodeI64x2LoadSplat] = gasMap[																	I64x2LoadSplat        	

	return opcode_costs
}
