package hosttest

import (
	"bytes"
	"fmt"
	"math/big"
	"sort"
	"testing"

	"github.com/ElrondNetwork/arwen-wasm-vm/v1_4/arwen"
	"github.com/ElrondNetwork/arwen-wasm-vm/v1_4/arwen/contexts"
	worldmock "github.com/ElrondNetwork/arwen-wasm-vm/v1_4/mock/world"
	test "github.com/ElrondNetwork/arwen-wasm-vm/v1_4/testcommon"
	testcommon "github.com/ElrondNetwork/arwen-wasm-vm/v1_4/testcommon"
	"github.com/ElrondNetwork/elrond-go-core/data/vm"
	logger "github.com/ElrondNetwork/elrond-go-logger"
	vmcommon "github.com/ElrondNetwork/elrond-vm-common"
	"github.com/ElrondNetwork/elrond-vm-common/parsers"
	"github.com/ElrondNetwork/elrond-vm-common/txDataBuilder"
	"github.com/stretchr/testify/require"
)

/*
	TODO - for second release of async, some of the tests here that start from the same base graph
	will be automaticaly generated by a comprehensive (not fuzzy-ing) test generation component
*/

var logAsync = logger.GetOrCreate("arwen/async")

func TestGraph_SyncCalls_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestSyncCalls()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_SyncCalls2_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestSyncCalls2()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_SyncCalls_FailPropagation_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestSyncCallsFailPropagation()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_OneAsyncCall_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestOneAsyncCall()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_OneAsyncCallCustomGasLocked_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestOneAsyncCallCustomGasLocked()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_OneAsyncCallNoCallback_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestOneAsyncCallNoCallback()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_OneAsyncCallFail_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestOneAsyncCallFail()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_OneAsyncCallNoCallbackFail_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestOneAsyncCallNoCallbackFail()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallIndirectFail_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestAsyncCallIndirectFail()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_OneAsyncCallbackFail_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestOneAsyncCallbackFail()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallbackIndirectFail_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestAsyncCallbackIndirectFail()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_OneAsyncCallCrossShard_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestOneAsyncCallCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_OneAsyncCallNoCallbackCrossShard_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestOneAsyncCallNoCallbackCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_OneAsyncCallCrossShard2_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestOneAsyncCallCrossShard2()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_OneAsyncCallFailCrossShard_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestOneAsyncCallFailCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_OneAsyncCallFailNoCallbackCrossShard_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestOneAsyncCallFailNoCallbackCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallIndirectFailCrossShard_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestAsyncCallIndirectFailCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_OneAsyncCallbackFailCrossShard_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestOneAsyncCallbackFailCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallbackIndirectFailCrossShard_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestAsyncCallbackIndirectFailCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCalls_CallGraph(t *testing.T) {
	// arwen.SetLoggingForTestsWithLogger("arwen/async")
	callGraph := test.CreateGraphTestTwoAsyncCalls()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsFirstNoCallback_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsFirstNoCallback()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsSecondNoCallback_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsSecondNoCallback()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsFirstFail_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsFirstFail()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsSecondFail_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsSecondFail()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsBothFail_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsBothFail()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsFirstCallbackFail_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsFirstCallbackFail()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsSecondCallbackFail_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsSecondCallbackFail()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsBothCallbacksFail_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsBothCallbacksFail()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCalls_LocalCross_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsLocalCross()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsFirstNoCallback_LocalCross_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncFirstNoCallbackCallsLocalCross()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsSecondNoCallback_LocalCross_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncSecondNoCallbackCallsLocalCross()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsFirstFail_LocalCross_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsFirstFailLocalCross()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsSecondFail_LocalCross_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsSecondFailLocalCross()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsBothFail_LocalCross_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsBothFailLocalCross()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsFirstCallbackFail_LocalCross_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsFirstCallbackFailLocalCross()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsSecondCallbackFail_LocalCross_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsSecondCallbackFailLocalCross()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsBothCallbacksFail_LocalCross_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsBothCallbacksFailLocalCross()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCalls_CrossLocal_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsCrossLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsFirstNoCallback_CrossLocal_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsFirstNoCallbackCrossLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsSecondNoCallback_CrossLocal_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsSecondNoCallbackCrossLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsFirstFail_CrossLocal_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsFirstFailCrossLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsSecondFail_CrossLocal_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsSecondFailCrossLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsBothFail_CrossLocal_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsBothFailCrossLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsFirstCallbackFail_CrossLocal_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsFirstCallbackFailCrossLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsSecondCallbackFail_CrossLocal_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsSecondCallbackFailCrossLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsBothCallbacksFail_CrossLocal_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsBothCallbacksFailCrossLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsCrossShard_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsFirstNoCallback_CrossShard_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsFirstNoCallbackCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsSecondNoCallback_CrossShard_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsSecondNoCallbackCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsFirstFailCrossShard_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsFirstFailCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsSecondFailCrossShard_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsSecondFailCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsBothFailCrossShard_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsBothFailCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsFirstCallbackFailCrossShard_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsFirstCallbackFailCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsSecondCallbackFailCrossShard_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsSecondCallbackFailCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_TwoAsyncCallsBothCallbacksFailCrossShard_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestTwoAsyncCallsBothCallbacksFailCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncsOnMultiLevelFail1_CallGraph(t *testing.T) {
	// TODO remove test for R2
	callGraph := test.CreateGraphTestAsyncCallsAsync()
	runGraphCallTestTemplateWithCustomAssertsConfig(t, callGraph, &assertsConfig{
		assertsAfterEachRootCall: noAssertsAfterEachRootCall,
		finalAsserts: func(t *testing.T, world *worldmock.MockWorld, expectedCallFinishData []*test.CallFinishDataItem, callsFinishData *test.CallsFinishData) {
			checkThatStoreIsEmpty(t, world)
			require.Equal(t, testcommon.ErrAsyncRegisterFail, callsFinishData.Data[1].FailError)
		},
	})
}

func TestGraph_AsyncsOnMultiLevelFail2_CallGraph(t *testing.T) {
	// TODO remove test for R2
	callGraph := test.CreateGraphTestSyncAndAsync5()
	runGraphCallTestTemplateWithCustomAssertsConfig(t, callGraph, &assertsConfig{
		assertsAfterEachRootCall: noAssertsAfterEachRootCall,
		finalAsserts: func(t *testing.T, world *worldmock.MockWorld, expectedCallFinishData []*test.CallFinishDataItem, callsFinishData *test.CallsFinishData) {
			checkThatStoreIsEmpty(t, world)
			require.Equal(t, testcommon.ErrAsyncRegisterFail, callsFinishData.Data[1].FailError)
		},
	})
}

func TestGraph_AsyncCallsAsync_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsync()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncFirstNoCallback_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncFirstNoCallback()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncSecondNoCallback_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncSecondNoCallback()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncFirstFail_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncFirstFail()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncFirstCallbackFail_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncFirstCallbackFail()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncSecondFail_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncSecondFail()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncSecondCallbackFail_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncSecondCallbackFail()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncBothCallbacksFail_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncBothCallbacksFail()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsync_CrossLocal_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncCrossLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncFirstNoCallback_CrossLocal_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncFirstNoCallbackCrossLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncSecondNoCallback_CrossLocal_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncSecondNoCallbackCrossLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncFirstFail_CrossLocal_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncFirstFailCrossLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncSecondFail_CrossLocal_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncSecondFailCrossLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncFirstCallbackFail_CrossLocal_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncFirstCallbackFailCrossLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncSecondCallbackFail_CrossLocal_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncSecondCallbackFailCrossLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncBothCallbacksFail_CrossLocal_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncBothCallbacksFailCrossLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsync_LocalCross_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncLocalCross()
	// TODO this is temp until R2
	runGraphCallTestTemplateWithCustomAssertsConfig(t, callGraph, assertsConfigForR1MultiLevel)
}

func TestGraph_AsyncCallsAsyncFirstNoCallback_LocalCross_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncFirstNoCallbackLocalCross()
	// TODO this is temp until R2
	runGraphCallTestTemplateWithCustomAssertsConfig(t, callGraph, assertsConfigForR1MultiLevel)
}

func TestGraph_AsyncCallsAsyncSecondNoCallback_LocalCross_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncSecondNoCallbackLocalCross()
	// TODO this is temp until R2
	runGraphCallTestTemplateWithCustomAssertsConfig(t, callGraph, assertsConfigForR1MultiLevel)
}

func TestGraph_AsyncCallsAsyncFirstFail_LocalCross_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncFirstFailLocalCross()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncSecondFail_LocalCross_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncSecondFailLocalCross()
	// TODO this is temp until R2
	runGraphCallTestTemplateWithCustomAssertsConfig(t, callGraph, assertsConfigForR1MultiLevel)
}

func TestGraph_AsyncCallsAsyncFirstCallbackFail_LocalCross_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncFirstCallbackFailLocalCross()
	// TODO this is temp until R2
	runGraphCallTestTemplateWithCustomAssertsConfig(t, callGraph, assertsConfigForR1MultiLevel)
}

func TestGraph_AsyncCallsAsyncSecondCallbackFail_LocalCross_CallGraph(t *testing.T) {
	// TODO matei-p activate in R2 - this fails in R1 due gas usage missmatch error that
	// prevents storage cleanup taking place
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncSecondCallbackFailLocalCross()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncBothCallbacksFail_LocalCross_CallGraph(t *testing.T) {
	// TODO matei-p activate in R2 - this fails in R1 due gas usage missmatch error that
	// prevents storage cleanup taking place
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncBothCallbacksFailLocalCross()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncCrossShard_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncFirstNoCallbackCrossShard_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncFirstNoCallbackCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncSecondNoCallbackCrossShard_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncSecondNoCallbackCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncFirstFailCrossShard_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncFirstFailCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncSecondFailCrossShard_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncSecondFailCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncFirstCallbackFailCrossShard_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncFirstCallbackFailCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncSecondCallbackFailCrossShard_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncSecondCallbackFailCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCallsAsyncBothCallbacksFailCrossShard_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsAsyncBothCallbacksFailCrossShard()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_DifferentTypeOfCallsToSameFunction_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestDifferentTypeOfCallsToSameFunction()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_SameContractWithDifferentSubCalls_LocalLocal_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestSameContractWithDifferentSubCallsLocalLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_SameContractWithDifferentSubCalls_LocalCross_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestSameContractWithDifferentSubCallsLocalCross()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_SameContractWithDifferentSubCalls_CrossLocal_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestSameContractWithDifferentSubCallsCrossLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_SameContractWithDifferentSubCalls_CrossCross_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestSameContractWithDifferentSubCallsCrossCross()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_CallbackCallsSync_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestCallbackCallsSync()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_CallbackCallsAsync_LocalLocal_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestCallbackCallsAsyncLocalLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_CallbackCallsAsyncFail_LocalLocal_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestCallbackCallsAsyncFailLocalLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_CallbackCallsAsyncCallbackFail_LocalLocal_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestCallbackCallsAsyncCallbackFailLocalLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_CallbackCallsAsync_LocalCross_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestCallbackCallsAsyncLocalCross()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_CallbackCallsAsyncFail_LocalCross_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestCallbackCallsAsyncFailLocalCross()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_CallbackCallsAsyncCallbackFail_LocalCross_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestCallbackCallsAsyncCallbackFailLocalCross()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_CallbackCallsAsync_CrossLocal_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestCallbackCallsAsyncCrossLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_CallbackCallsAsyncFail_CrossLocal_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestCallbackCallsAsyncFailCrossLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_CallbackCallsAsyncCallbackFail_CrossLocal_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestCallbackCallsAsyncCallbackFailCrossLocal()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_CallbackCallsAsync_CrossCross_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestCallbackCallsAsyncCrossCross()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_CallbackCallsAsyncFail_CrossCross_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestCallbackCallsAsyncFailCrossCross()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_CallbackCallsAsyncCallbackFail_CrossCross_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestCallbackCallsAsyncCallbackFailCrossCross()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_SyncAndAsync1_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestSyncAndAsync1()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_SyncAndAsync2_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestSyncAndAsync2()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_SyncAndAsync3_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestSyncAndAsync3()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_SyncAndAsync4_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestSyncAndAsync4()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_SyncAndAsync5_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestSyncAndAsync5()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_SyncAndAsync6_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestSyncAndAsync6()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_SyncAndAsync7_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestSyncAndAsync7()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_SyncAndAsync8_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestSyncAndAsync8()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_SyncAndAsync9_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestSyncAndAsync9()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_SyncAndAsync10_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestSyncAndAsync10()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_SyncAndAsync11_CallGraph(t *testing.T) {
	callGraph := test.CreateGraphTestSyncAndAsync11()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCall2_CrossShard_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsCrossShard2()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCall3_CrossShard_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsCrossShard3()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCall4_CrossShard_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsCrossShard4()
	// TODO this is temp until R2
	runGraphCallTestTemplateWithCustomAssertsConfig(t, callGraph, assertsConfigForR1MultiLevel)
}

func TestGraph_AsyncCall5_CrossShard_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsCrossShard5()
	// TODO this is temp until R2
	runGraphCallTestTemplateWithCustomAssertsConfig(t, callGraph, assertsConfigForR1MultiLevel)
}

func TestGraph_AsyncCall6_CrossShard_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsCrossShard6()
	// TODO this is temp until R2
	runGraphCallTestTemplateWithCustomAssertsConfig(t, callGraph, assertsConfigForR1MultiLevel)
}

func TestGraph_AsyncCall7_CrossShard_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsCrossShard7()
	runGraphCallTestTemplate(t, callGraph)
}

func TestGraph_AsyncCall8_CrossShard_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsCrossShard8()
	// TODO this is temp until R2
	runGraphCallTestTemplateWithCustomAssertsConfig(t, callGraph, assertsConfigForR1MultiLevel)
}

func TestGraph_AsyncCall9_CrossShard_CallGraph(t *testing.T) {
	t.Skip("multi-level only")
	callGraph := test.CreateGraphTestAsyncCallsCrossShard9()
	// TODO this is temp until R2
	runGraphCallTestTemplateWithCustomAssertsConfig(t, callGraph, assertsConfigForR1MultiLevel)
}

type assertsConfig struct {
	assertsAfterEachRootCall func(*test.TestCallNode, *worldmock.MockWorld, *test.VMOutputVerifier, []string)
	finalAsserts             func(t *testing.T, world *worldmock.MockWorld, expectedCallFinishData []*test.CallFinishDataItem, callsFinishData *test.CallsFinishData)
}

var noAssertsAfterEachRootCall = func(*test.TestCallNode, *worldmock.MockWorld, *test.VMOutputVerifier, []string) {}

var assertsConfigForR1MultiLevel = &assertsConfig{
	assertsAfterEachRootCall: noAssertsAfterEachRootCall,
	finalAsserts: func(t *testing.T, world *worldmock.MockWorld, expectedCallFinishData []*test.CallFinishDataItem, callsFinishData *test.CallsFinishData) {
		checkCallFinishDataForGraphTesting(t, expectedCallFinishData, callsFinishData.Data)
	},
}

func runGraphCallTestTemplate(t *testing.T, callGraph *test.TestCallGraph) {
	// regular tests, with full asserts
	runGraphCallTestTemplateWithCustomAssertsConfig(t, callGraph, &assertsConfig{
		assertsAfterEachRootCall: func(startNode *test.TestCallNode, world *worldmock.MockWorld, verify *test.VMOutputVerifier, expectedErrorsForRound []string) {
			if startNode.ErrFail == nil {
				verify.Ok().
					HasRuntimeErrors(expectedErrorsForRound...)
				// TODO matei-p will be implemented in R2
				// GasRemaining(callGraph.StartNode.GasLimit - totalGasUsed)
			} else {
				verify.ReturnCode(vmcommon.ExecutionFailed).
					GasRemaining(0).
					HasRuntimeErrors(expectedErrorsForRound...)
			}
		},
		finalAsserts: func(t *testing.T, world *worldmock.MockWorld, expectedCallFinishData []*test.CallFinishDataItem, callsFinishData *test.CallsFinishData) {
			checkThatStoreIsEmpty(t, world)
			checkCallFinishDataForGraphTesting(t, expectedCallFinishData, callsFinishData.Data)
		},
	})
}

func runGraphCallTestTemplateWithCustomAssertsConfig(t *testing.T, callGraph *test.TestCallGraph, assertsConfig *assertsConfig) {
	testConfig := makeTestConfig()
	testConfig.GasProvided = callGraph.StartNode.GasLimit
	testConfig.GasLockCost = test.DefaultCallGraphLockedGas

	executionGraph := callGraph.CreateExecutionGraphFromCallGraph()

	gasGraph := executionGraph.ComputeGasGraphFromExecutionGraph()
	gasGraph.PropagateSyncFailures()
	gasGraph.AssignExecutionRounds(t)
	gasGraph.ComputeRemainingGasBeforeCallbacks(t)
	gasGraph.ComputeRemainingGasAfterCallbacks()

	startNode := gasGraph.GetStartNode()
	crossShardCallsQueue := test.NewCrossShardCallQueue()
	crossShardCallsQueue.Enqueue(test.UserAddress, startNode, vm.DirectCall, []byte{})

	computeCallIDs(gasGraph)

	// compute execution order (return data) assertions and compute gas assertions
	expectedCallFinishData := computeExpectedValues(gasGraph)

	// graph gas sanity check
	totalGasUsed, totalGasRemaining := computeExpectedTotalGasValues(gasGraph)
	require.Equal(t, int(gasGraph.StartNode.GasLimit), int(totalGasUsed+totalGasRemaining), "Expected Gas Sanity Check")

	crtTxNumber := 0

	var currentVMOutput *vmcommon.VMOutput

	runtimeConfigsForCalls := make(map[string]*test.RuntimeConfigOfCall)
	callsFinishData := &test.CallsFinishData{
		Data: make([]*test.CallFinishDataItem, 0),
	}

	world := worldmock.NewMockWorld()

	// create contracts
	mockInstancesTestTemplate := test.BuildMockInstanceCallTest(t).
		WithContracts(
			test.CreateMockContractsFromAsyncTestCallGraph(callGraph, callsFinishData, runtimeConfigsForCalls, testConfig)...,
		)
	contractsInitialized := false

	var crossShardCall *test.CrossShardCall
	for !crossShardCallsQueue.IsEmpty() {
		crossShardCall = crossShardCallsQueue.Dequeue()
		startNode = crossShardCall.StartNode

		crtTxNumber++
		crtTxHash := big.NewInt(int64(crtTxNumber)).Bytes()
		crossShardCall.StartNode.CrtTxHash = crtTxHash

		expectedErrorsForRound := computeExpectedErrorsForRound(gasGraph, startNode)

		arguments := [][]byte{}
		if len(crossShardCall.Data) != 0 {
			_, parsedArguments, err := parsers.NewCallArgsParser().ParseData(string(crossShardCall.Data))
			if err != nil {
				panic(err)
			}
			arguments = parsedArguments
		}

		currentVMOutput, _ = mockInstancesTestTemplate.
			WithInput(test.CreateTestContractCallInputBuilder().
				WithCallerAddr(crossShardCall.CallerAddress).
				WithRecipientAddr([]byte(startNode.Call.ContractAddress)).
				WithFunction(startNode.Call.FunctionName).
				WithGasProvided(startNode.GasLimit).
				WithGasLocked(startNode.GasLocked).
				WithCallType(crossShardCall.CallType).
				WithArguments(arguments...).
				WithPrevTxHash(big.NewInt(int64(crtTxNumber-1)).Bytes()).
				WithCurrentTxHash(crtTxHash).
				Build()).
			WithSetup(func(host arwen.VMHost, world *worldmock.MockWorld) {
				world.SelfShardID = world.GetShardOfAddress(startNode.Call.ContractAddress)
				setZeroCodeCosts(host)
				setAsyncCosts(host, testConfig.GasLockCost)
			}).
			AndAssertResultsWithWorld(world, !contractsInitialized, startNode, expectedErrorsForRound,
				assertsConfig.assertsAfterEachRootCall)
		contractsInitialized = true

		extractAndPersistStores(t, world, currentVMOutput)

		crossShardEdges := getCrossShardEdgesFromSubtree(gasGraph, startNode, crossShardCallsQueue)
		extractOuptutTransferCalls(currentVMOutput, crossShardEdges, crossShardCallsQueue)
	}

	if assertsConfig.finalAsserts != nil {
		assertsConfig.finalAsserts(t, world, expectedCallFinishData, callsFinishData)
	}
}

func computeExpectedErrorsForRound(gasGraph *test.TestCallGraph, startNode *test.TestCallNode) []string {
	visits := make(map[uint]bool)
	expectedErrorsForRound := make([]string, 0)
	gasGraph.DfsGraphFromNode(startNode, func(path []*test.TestCallNode, parent *test.TestCallNode, node *test.TestCallNode, incomingEdge *test.TestCallEdge) *test.TestCallNode {
		if node.ExecutionRound != startNode.ExecutionRound {
			return node
		}
		edge := node.IncomingEdge
		if edge != nil && edge.CallbackFail == true {
			// for cross shard callbacks will detect error in their execution round
			return node
		}
		if edge != nil && edge.ErrFail != nil {
			expectedErrorsForRound = append(expectedErrorsForRound, edge.ErrFail.Error())
		}
		return node
	}, visits, false /* don't followCrossShardEdges */)
	return expectedErrorsForRound
}

func checkThatStoreIsEmpty(t testing.TB, world *worldmock.MockWorld) {
	for address, account := range world.AcctMap {
		for key, value := range account.Storage {
			require.Equal(t, []byte{}, value, fmt.Sprintf("Value present in storage for address '%s' key '%s'", address, key))
		}
	}
}

func getCrossShardEdgesFromSubtree(gasGraph *test.TestCallGraph, startNode *test.TestCallNode, crossShardCallsQueue *test.CrossShardCallsQueue) []*test.TestCallEdge {
	crossShardEdges := make([]*test.TestCallEdge, 0)
	visits := make(map[uint]bool)
	gasGraph.DfsGraphFromNode(startNode, func(path []*test.TestCallNode, parent *test.TestCallNode, node *test.TestCallNode, incomingEdge *test.TestCallEdge) *test.TestCallNode {
		for _, edge := range node.AdjacentEdges {
			if edge.Type == test.AsyncCrossShard || edge.Type == test.CallbackCrossShard {
				crossShardEdges = append(crossShardEdges, edge)
			}
		}
		return node
	}, visits, false /* don't followCrossShardEdges */)

	// if a parent context async exists, add it's callback edge also
	incomingEdgeType := startNode.GetIncomingEdgeType()
	if incomingEdgeType == test.CallbackCrossShard &&
		startNode.Parent != nil && startNode.Parent.Parent != nil {
		prevPrevNode := startNode.Parent.Parent
		if prevPrevNode.IsAsync() {
			for _, edge := range prevPrevNode.AdjacentEdges {
				if edge.Type == test.Callback || edge.Type == test.CallbackCrossShard {
					crossShardEdges = append(crossShardEdges, edge)
				}
			}
		}
	}

	return crossShardEdges
}

func executionOrderTraversal(gasGraph *test.TestCallGraph, nodeProcessing func(node *test.TestCallNode)) {
	sortedNodes := make(NodesList, 0)
	for _, node := range gasGraph.Nodes {
		if node.WillNotExecute() {
			continue
		}
		sortedNodes = append(sortedNodes, node)
	}
	sort.Stable(sortedNodes)

	for _, node := range sortedNodes {
		nodeProcessing(node)
	}
}

type NodesList []*test.TestCallNode

func (nodes NodesList) Len() int           { return len(nodes) }
func (nodes NodesList) Less(i, j int) bool { return nodes[i].ExecutionRound < nodes[j].ExecutionRound }
func (nodes NodesList) Swap(i, j int)      { nodes[i], nodes[j] = nodes[j], nodes[i] }

func computeCallIDs(gasGraph *test.TestCallGraph) {
	executionOrderTraversal(gasGraph, func(node *test.TestCallNode) {
		if node.IsLeaf() || node.Parent == nil {
			return
		}

		var parent *test.TestCallNode
		if node.GetIncomingEdgeType() == test.Callback {
			parent = node.Parent.Parent
		} else {
			parent = node.Parent
		}

		if parent != nil {
			parent.NonGasEdgeCounter++
			newCallID := append(parent.Call.CallID, big.NewInt(parent.NonGasEdgeCounter).Bytes()...)
			newCallID, _ = gasGraph.Crypto.Sha256(newCallID)
			node.Call.CallID = newCallID
		}
	})

}

func computeExpectedValues(gasGraph *test.TestCallGraph) []*test.CallFinishDataItem {
	expectedCallsFinishData := make([]*test.CallFinishDataItem, 0)

	executionOrderTraversal(gasGraph, func(node *test.TestCallNode) {
		parent := node.Parent
		if !node.IsLeaf() {
			return
		}

		if parent.Call.FunctionName == test.FakeCallbackName {
			return
		}

		expectedCallFinishData := &test.CallFinishDataItem{
			ContractAndFunction: string(parent.Call.ContractAddress) + "_" + parent.Call.FunctionName + test.TestReturnDataSuffix,
			GasProvided:         parent.GasLimit,
			GasRemaining:        parent.GasRemaining,
			FailError:           parent.ErrFail,
		}

		expectedCallsFinishData = append(expectedCallsFinishData, expectedCallFinishData)
		return
	})

	return expectedCallsFinishData
}

func computeExpectedTotalGasValues(graph *test.TestCallGraph) (uint64, uint64) {
	visits := make(map[uint]bool)
	totalGasUsed := uint64(0)
	totalGasRemaining := uint64(0)

	graph.DfsFromNodeUntilFailures(graph.StartNode.Parent, graph.StartNode, nil, make([]*test.TestCallNode, 0),
		func(path []*test.TestCallNode, parent *test.TestCallNode, node *test.TestCallNode, incomingEdge *test.TestCallEdge) *test.TestCallNode {
			if node.IsLeaf() {
				// fmt.Printf("node %s used %d\n", node.VisualLabel, node.GasUsed)
				totalGasUsed += node.GasUsed
				return node
			}

			// all gas is used for failed calls
			if (parent == nil && node.HasFailSyncEdge()) ||
				node.IsIncomingEdgeFail() {
				// fmt.Printf("failed %s used %d\n", node.VisualLabel, node.GasLimit)
				totalGasUsed += node.GasLimit
				return node
			}

			if parent == nil {
				totalGasRemaining += node.GasRemaining + node.GasAccumulated
			} else if node.IsCallback() || (node.IsAsync() && !node.HasCallback()) {
				totalGasRemaining += node.GasAccumulated
			}

			return node
		}, visits)

	return totalGasUsed, totalGasRemaining
}

func extractOuptutTransferCalls(vmOutput *vmcommon.VMOutput, crossShardEdges []*test.TestCallEdge, crossShardCallsQueue *test.CrossShardCallsQueue) {
	for _, crossShardEdge := range crossShardEdges {
		edgeToAddress := string(crossShardEdge.To.Call.ContractAddress)
		for _, outputAccount := range vmOutput.OutputAccounts {
			transferDestinationAddress := string(outputAccount.Address)
			if edgeToAddress != transferDestinationAddress {
				continue
			}
			for _, outputTransfer := range outputAccount.OutputTransfers {
				callType := outputTransfer.CallType

				argParser := parsers.NewCallArgsParser()
				function, parsedArgs, _ := argParser.ParseData(string(outputTransfer.Data))

				callID := parsedArgs[0]

				var encodedArgs []byte
				if bytes.Equal(callID, crossShardEdge.To.Call.CallID) {
					logAsync.Trace("Found transfer",
						"sender", string(outputTransfer.SenderAddress),
						"to", string(outputAccount.Address),
						"gas limit", outputTransfer.GasLimit,
						"callType", callType,
						"data", contexts.DebugCallIDAsString(outputTransfer.Data))
					if callType == vm.AsynchronousCall {
						encodedArgs = outputTransfer.Data
					} else if callType == vm.AsynchronousCallBack {
						callData := txDataBuilder.NewBuilder()
						callData.Func(function)
						for _, arg := range parsedArgs {
							callData.Bytes(arg)
						}
						encodedArgs = callData.ToBytes()
					}
					crossShardCallsQueue.Enqueue(outputTransfer.SenderAddress, crossShardEdge.To, callType, encodedArgs)
				}
			}
		}
	}
}

func extractAndPersistStores(t testing.TB, world *worldmock.MockWorld, vmOutput *vmcommon.VMOutput) {
	// check if accounts with storage from OutputAccounts have the same shardID as world mock
	for _, outputAccount := range vmOutput.OutputAccounts {
		if len(outputAccount.StorageUpdates) != 0 {
			require.Equal(t, world.SelfShardID, world.GetShardOfAddress(outputAccount.Address), fmt.Sprintf("Incorrect shard for account with address '%s'", string(outputAccount.Address)))
		}
	}

	world.UpdateAccounts(vmOutput.OutputAccounts, nil)
}

func extractGasUsedPerContract(vmOutput *vmcommon.VMOutput, gasUsedPerContract map[string]uint64) {
	for _, outputAccount := range vmOutput.OutputAccounts {
		if _, ok := gasUsedPerContract[string(outputAccount.Address)]; !ok {
			gasUsedPerContract[string(outputAccount.Address)] = 0
		}
		gasUsedPerContract[string(outputAccount.Address)] += outputAccount.GasUsed
	}
}

func checkCallFinishDataForGraphTesting(t testing.TB, expectedCallsFinishData []*test.CallFinishDataItem, callsFinishData []*test.CallFinishDataItem) {
	require.Equal(t, len(expectedCallsFinishData), len(callsFinishData), "CallFinishData length")
	for idx := range expectedCallsFinishData {
		expectedCallFinishData := expectedCallsFinishData[idx]
		actualCallFinishData := callsFinishData[idx]
		require.Equal(t, expectedCallFinishData.ContractAndFunction, actualCallFinishData.ContractAndFunction, "CallFinishData - Call")
		require.Equal(t, int(expectedCallFinishData.GasProvided), int(actualCallFinishData.GasProvided), fmt.Sprintf("CallFinishData - Gas Limit for '%s'", actualCallFinishData.ContractAndFunction))
		require.Equal(t, int(expectedCallFinishData.GasRemaining), int(actualCallFinishData.GasRemaining), fmt.Sprintf("CallFinishData - Gas Remaining for '%s'", actualCallFinishData.ContractAndFunction))
		require.Equal(t, expectedCallFinishData.FailError, actualCallFinishData.FailError, fmt.Sprintf("CallFinishData - Fail error for '%s'", actualCallFinishData.ContractAndFunction))
	}
}

func CheckUsedGasPerContract(t testing.TB, expectedGasUsagePerContract map[string]uint64, gasUsedPerContract map[string]uint64) {
	for expectedContract, expectedGas := range expectedGasUsagePerContract {
		require.Equal(t, int(expectedGas), int(gasUsedPerContract[expectedContract]), fmt.Sprintf("Used gas for contract %s", expectedContract))
	}
}
