package elrondapigenerate

import (
	"fmt"
	"os"
)

func autoGeneratedHeader(out *os.File) {
	out.WriteString(`// Code generated by elrondapi generator. DO NOT EDIT.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!! AUTO-GENERATED FILE !!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
`)
}

func autoGeneratedGoHeader(out *os.File, packageName string) {
	out.WriteString(fmt.Sprintf(`package %s

`, packageName))
	autoGeneratedHeader(out)
}
