package elrondapigenerate

import (
	"fmt"
	"os"
)

func WriteRustVMHooksPointers(out *os.File, eiMetadata *EIMetadata) {
	out.WriteString(`// Code generated by elrondapi generator. DO NOT EDIT.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!! AUTO-GENERATED FILE !!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

use std::ffi::c_void;

#[repr(C)]
pub struct vm_exec_vm_hook_pointers {
`)

	for _, funcMetadata := range eiMetadata.AllFunctions {
		out.WriteString(fmt.Sprintf(
			"    pub %s: extern \"C\" fn%s",
			snakeCase(funcMetadata.Name),
			writeRustFnArguments(
				"context: *mut c_void",
				funcMetadata,
			),
		))

		out.WriteString(",\n")
	}

	out.WriteString("}\n")
}
