package elrondapigenerate

import (
	"fmt"
	"os"
)

func WriteNames(out *os.File, eiMetadata *EIMetadata) {
	out.WriteString(`package wasmer2

// Code generated by elrondapi generator. DO NOT EDIT.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!! AUTO-GENERATED FILE !!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

var empty struct{}

var functionNames = map[string]struct{}{`)

	for _, funcMetadata := range eiMetadata.AllFunctions {
		out.WriteString(fmt.Sprintf("\n\t\"%s\": empty,", lowerInitial(funcMetadata.Name)))
	}

	out.WriteString(`
}
`)
}
