package elrondapigenerate

import (
	"fmt"
	"os"
)

func WriteNames(out *os.File, eiMetadata *EIMetadata) {
	autoGeneratedGoHeader(out, "wasmer2")
	out.WriteString(`
var empty struct{}

var functionNames = map[string]struct{}{`)

	for _, funcMetadata := range eiMetadata.AllFunctions {
		out.WriteString(fmt.Sprintf("\n\t\"%s\": empty,", lowerInitial(funcMetadata.Name)))
	}

	out.WriteString(`
}
`)
}
