package elrondapigenerate

import (
	"fmt"
	"os"
)

func WriteRustWasmerImports(out *os.File, eiMetadata *EIMetadata) {
	out.WriteString(`// Code generated by elrondapi generator. DO NOT EDIT.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!! AUTO-GENERATED FILE !!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

use wasmer::{imports, Function, ImportObject, Store};

use crate::wasmer_env_2::VMHooksWrapper;

`)

	for _, funcMetadata := range eiMetadata.AllFunctions {
		out.WriteString(fmt.Sprintf(
			"fn %s%s",
			wasmerImportAdapterFunctionName(funcMetadata.Name),
			writeRustFnDeclarationArguments(
				"env: &VMHooksWrapper",
				funcMetadata,
			),
		))

		out.WriteString(" {\n")
		out.WriteString(fmt.Sprintf("    env.vm_hooks.%s(", snakeCase(funcMetadata.Name)))

		for i, arg := range funcMetadata.Arguments {
			if i > 0 {
				out.WriteString(", ")
			}
			out.WriteString(snakeCase(arg.Name))
		}

		out.WriteString(")\n}\n\n")
	}

	out.WriteString(`pub fn convert_imports_2(store: &Store, env: VMHooksWrapper) -> ImportObject {
    imports! {
        "env" => {
`)

	for _, funcMetadata := range eiMetadata.AllFunctions {
		out.WriteString(fmt.Sprintf(
			"            \"%s\" => Function::new_native_with_env(store, env.clone(), %s),\n",
			lowerInitial(funcMetadata.Name),
			wasmerImportAdapterFunctionName(funcMetadata.Name),
		))
	}

	out.WriteString(`
        }
    }
}
`)

}
