package elrondapigenerate

import (
	"bufio"
	"fmt"
	"os"
)

// WriteOpcodeCost generates code for opcodeCostWasmer2.go
func WriteOpcodeCost(out *os.File) {
	out.WriteString(`// Code generated by elrondapi generator. DO NOT EDIT.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!! AUTO-GENERATED FILE !!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

`)
	out.WriteString("package executor\n\n")
	out.WriteString("type OpcodeCostWasmer2 struct {\n")

	readFile, err := os.Open("generate/opcodes.txt")
	if err != nil {
		panic(err)
	}
	defer readFile.Close()

	fileScanner := bufio.NewScanner(readFile)
	fileScanner.Split(bufio.ScanLines)

	for fileScanner.Scan() {
		opcode := fileScanner.Text()
		out.WriteString(fmt.Sprintf("\t%-30suint32\n", opcode))
	}
	out.WriteString("}\n")
}
