package elrondapigenerate

import (
	"bufio"
	"fmt"
	"os"
)

// WriteOpcodeCost generates code for wasmer2/opcodeCost.go
func WriteOpcodeCost(out *eiGenWriter) {
	out.WriteString(`// Code generated by elrondapi generator. DO NOT EDIT.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!! AUTO-GENERATED FILE !!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

`)
	out.WriteString("package wasmer2\n\n")
	out.WriteString("type OpcodeCost struct {\n")

	readFile, err := os.Open("generate/cmd/input/wasmer2_opcodes.txt")
	if err != nil {
		panic(err)
	}
	defer readFile.Close()

	fileScanner := bufio.NewScanner(readFile)
	fileScanner.Split(bufio.ScanLines)

	for fileScanner.Scan() {
		opcode := fileScanner.Text()
		out.WriteString(fmt.Sprintf("\t%-30suint32\n", opcode))
	}
	out.WriteString("}\n")
}
